### ISSUE TITLE
def face_corners(self, fkey):

### ISSUE THREAD

**Issue by Rippmann** [compas-dev/compas#1]
In the heat of the moment I accidently confused it with "def face_vertices". @brgcode What are face corners? Descriptive docstring missing.

And lets give face_coordinates and optional ordered=True arg.

**Comment by tomvanmele** [comment]
face corners are triplets of points corresponding to the corners of the face.
it is just there for convenience.
think of it as: face_vertices (1) > face_halfedges (2) > face_corners (3).

face_vertices are always ordered in the new/current implementation of the mesh, so face_coordinates are as well...
