### ISSUE TITLE
gh_python.MeshArtist doesn't work

### ISSUE THREAD

**Issue by baolianliu** [compas-dev/compas#1037]
**Describe the bug**
When I created a mesh in COMPAS_singular, I want to visualize the mesh by ghpython.MeshArtist.draw( ), it doesn't work. Is there anything missing?

**Screenshots**
![image](https://user-images.githubusercontent.com/91332357/164476627-edccb0a6-2555-40f4-bfb1-15c20c622bda.png)

**Desktop (please complete the following information):**
 - Windows10, Rhino7
 - Python version 3.9.6
 - Python package manager [pip, conda]

**Comment by gonzalocasas** [comment]
is `densemesh` a `compas.datastructures.Mesh`?

**Comment by gonzalocasas** [comment]
also, please add the version of compas that you're using.

**Comment by baolianliu** [comment]
> is `densemesh` a `compas.datastructures.Mesh`?

No, densemesh is from compas_singular.get_quad_mesh( )

**Comment by baolianliu** [comment]
> is `densemesh` a `compas.datastructures.Mesh`?

COMPAS version is 1.15.1

**Comment by gonzalocasas** [comment]
In that case, i think this should be reported in the https://github.com/BlockResearchGroup/compas_singular repository
