### ISSUE TITLE
mesh_subdivide_quad trying to access mesh.halfedges

### ISSUE THREAD

**Issue by andrewliew** [compas-dev/compas#105]
Bug in develop branch:

Message: 'Mesh' object has no attribute 'halfedges'

Traceback:
  line 143, in mesh_subdivide_quad, "F:\compas\src\compas\topology\subdivision.py"
  line 97, in mesh_subdivide, "F:\compas\src\compas\topology\subdivision.py"

When mesh_subdivide_quad tries to access subd.halfedges()

**Comment by tomvanmele** [comment]
fixed on develop
