### ISSUE TITLE
 set_edge_attributes(self, key, names, values)  wrong parameter descritpion.

### ISSUE THREAD

**Issue by Rippmann** [compas-dev/compas#111]
def set_edge_attributes(self, key, names, values):
        """Set multiple attributes of one edge.

        Parameters
        ----------
        key : tuple, list
            The identifier of the edge, in the form of a pair of vertex identifiers.
        **attr_dict : dict (None)
            A dictionary of attributes as name-value pairs.**

However, would a attr_dict not make more sense?

**Comment by tomvanmele** [comment]
the parameter descriptions are indeed outdated. in my opinion, it is more consistent with the other functions to ask for and provide names and values. otherwise the syntax is completely different for one v multiple attributes...

```python
mesh.set_edge_attribute((0, 1), 'q', 1.0)
mesh.set_edge_attributes((0, 1), ('q', 'f'), (1.0, 2.0))
```
