### ISSUE TITLE
Polygon modifies the inputs in-place

### ISSUE THREAD

**Issue by funkchaser** [compas-dev/compas#1112]
**Describe the bug**
The constructor of `compas.geometry.Polygon` seems to modify the list of points it takes as input if the first and the last point are identical, e.g. when creating a `Polygon` from a closed `Polyline` . Hence it effectively modifies the input polyline or the input list. This is undesirable.

**To Reproduce**
using compas  1.17.4

```
from compas.geometry import Polyline
from compas.geometry import Polygon

pts = [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0], [0, 0, 0]]

# Example with Polyline --> Polygon
polyline = Polyline(pts)
print("n pts:", len(polyline.points))  # >>> 5
print("closed:", polyline.is_closed())  # >>> True

polygon = Polygon(polyline.points)
print("n pts:", len(polyline.points))  # >>> 4
print("closed:", polyline.is_closed())  # >>> False

# Example with a list only
print("n pts:", len(pts))  # >>> 5
polygon = Polygon(pts)
print("n pts:", len(pts))  # >>> 4
```

**Expected behavior**
The input object should not be modified, e.g. `Polygon` should copy the list before removing items.

**Comment by gonzalocasas** [comment]
Yep, something's off there, I'll take a look at it!
