### ISSUE TITLE
Update `black`

### ISSUE THREAD

**Issue by chenkasirer** [compas-dev/compas#1117]
Due to added/changing rules in version [23.1.0](https://black.readthedocs.io/en/stable/change_log.html#id1) which break the build the version is now pinned to 22.12.0. See https://github.com/compas-dev/compas/pull/1116.

This is a reminder as @gonzalocasas pointed we should aim at updating to the latest `black` at our earliest convenience.

**Comment by jf---** [comment]
@tomvanmele if you go with `ruff` over `black`, then pls close. Since `black` is integrated in CI, perhaps just close right away?

**Comment by tomvanmele** [comment]
in any case, i think the particular issue has been resolved in the meantime...
