### ISSUE TITLE
Polyline not drawing on gh

### ISSUE THREAD

**Issue by katarametin** [compas-dev/compas#1122]
**Describe the bug**
I tried to draw a Polyline in grasshopper, and it shows only the points.

**To Reproduce**
```
from compas.geometry import Polyline
from compas.geometry import Point
from compas.artists import Artist
pt1 = [3, 4, 0]
pt2 = Point(2, 3, 2)
pt3 = [5, 6, 9]
compas_polyline = Polyline([pt1, pt2, pt3])
a = Artist(compas_polyline).draw()
```

**Screenshots**
![image](https://user-images.githubusercontent.com/91249451/222238306-57c1c5bb-9963-4c6e-97c2-374011774108.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Python version: iron python 2.7

**Comment by gonzalocasas** [comment]
ah, this is caused by https://discourse.mcneel.com/t/polyline-output-wanted-but-got-a-list-of-points/77509
i'll fix it tomorrow
