### ISSUE TITLE
GA solver example

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#114]
here are some errors/typos I received or saw:

(1) under "if __name__ == '__main__':" in ga.py
line 944: compas.temp does not exist

(2) under 'def visualize_evolution'
line 258: change "vis= Ga_Plotter()" to "vis=GaPlotter()"

**Comment by tomvanmele** [comment]
reference to ga plotter should be fixed.
temp folder should not be issue.
please check and close if fixed...
