### ISSUE TITLE
Precision system

### ISSUE THREAD

**Issue by chenkasirer** [compas-dev/compas#1140]
Related to: https://github.com/compas-dev/compas/pull/1057#discussion_r921978062

Some kind of a precision system can be useful which allows user to:
- get/set a globally desired unit (mm/meter/cm etc.)
- get/set a local version of the above
- get/set the desired tolerance for each

This would replace all sorts of local tolerance which aren't standardized and are defined per module/class/instance. 
Maybe in form of a `Precision` mixin which will by default fetch values from a global default and allow setting a modified local copy thereof.

**Comment by gonzalocasas** [comment]
I always felt we needed to add built-in/native support for units across the board. Something like what `astropy` does: https://docs.astropy.org/en/stable/units/index.html

Because, well, it's important :) 

![Image](https://user-images.githubusercontent.com/933277/235982064-d1df4905-910f-494e-85cb-c31a23da4764.png)

**Comment by jf---** [comment]
@tomvanmele I think this can be closed with the Precision class being added in 2.0

**Comment by yck011522** [comment]
@jf--- as far as I understand, the new Precision class solves the tolerance problem but did not really solve the lack of units problem that @gonzalocasas  mentioned.

**Comment by jf---** [comment]
Gotcha, thanks for pointing out. But that seems another issue altogether: precision and metric(s) and 2 separate issues of concern.

**Comment by gonzalocasas** [comment]
Closing this and opened #1319 for the units idea/discussion
