### ISSUE TITLE
Call functions.principal_stresses(data) with a specific length of data fails

### ISSUE THREAD

**Issue by WeberMarius** [compas-dev/compas#1142]
I try to use the functions.principal_stresses (data) via proxy server with a dummy dataset x using Rhino: 

 x = range(55)
 for n in x:
      data=n
      output=functions.principal_stresses(data)

I changed the function principal_stresses so that data=n only put the data in the output (see below).

def principal_stresses(data):
    """ Performs principal stress calculations solving the eigenvalues problem.
    Parameters
    ----------
    data : dic
        Element data from structure.results for the Step.
    Returns
    -------
    spr: dict
        dictionary with the principal stresses of each element organised per
        `stress_type` ('max', 'min') and `section_point` ('sp1, 'sp5').
        {section_point: {stress_type: array([element_0, elemnt_1, ...])}}
    e: dict
        dictionary with the principal stresses vector components in World coordinates
        of each element organised per `stress_type` ('max', 'min') and
        `section_point` ('sp1, 'sp5').
        {section_point: {stress_type: array([element_0_x, elemnt_1_x, ...],
        [element_0_y, elemnt_1_y, ...])}}
    Warnings
    --------
    The function is experimental and works only for shell elements at the moment.
    """
    output=data
    return output

If i run x to range(50) the workflow works fine. If i rund x to range(60) Rhinio freezes. Could someone help me out of this? Maybe it's because the proxyserver stopped? (although I let it open). Thanks for any advices

**Comment by jf---** [comment]
@tomvanmele pls close
