### ISSUE TITLE
intersection_lines_xy has confusing input and output

### ISSUE THREAD

**Issue by tomvanmele** [compas-dev/compas#12]
it is unclear if the function only returns an intersection point if all lines intersect at one point, or all intersection points between pairs of lines in the set.

**Comment by tomvanmele** [comment]
the current implementation has been replaced by a NotImplementedError...

**Comment by tomvanmele** [comment]
it should return one approximate intersection point

**Comment by Rippmann** [comment]
I would suggest to return all points of all possible intersections. I would leave it to the user to then compute the barycenter etc. Not sure how useful such a function is... especially if you give it more than three lines. You quickly get intersection points far away from an approximate intersection. The pairwise comparison in the current code suggests that the lines are given in a particular order. I would assume that this is not the general case. I would suggest to simply return all possible intersections or just scratch the function.

**Comment by tomvanmele** [comment]
okay the function has been removed.
there is a gist with an implementation based on numpy for finding the "best-fit" intersection of four non-concurrent lines. 

https://gist.github.com/brgcode/0fc54568ca2bf51044a2a9d52db8fcb3
