### ISSUE TITLE
VTK Viewer import error when PyQt5 is not installed

### ISSUE THREAD

**Issue by tmsmendez** [compas-dev/compas#121]
Importing any function from the compas.viewers function rises the exception: ''Error with PyQt5 import'', if you do not have PyQt5 installed. This exception is only relevant for users of the VtkViewer. As a fix I have try-excepted the importing of the VtkViewer in the compas.viewers __init__ file, but perhaps there is a better solution.

**Comment by andrewliew** [comment]
Removed the printing of the import fail, it will simply pass now if PyQt5 is not available.
