### ISSUE TITLE
Question: should imports really fail if an optimized (e.g. numpy-based) version fails when there's a pure python version?

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#122]
Right now, importing the `compas.geometry` package on CPython is impossible if `numpy` and `scipy` are not installed. The imports are `try..except`'ed and they only fail if it's not IronPython, which sort of makes sense considering `numpy` and `scipy` will be explicit dependencies installed with the installer pretty soon.

However, it feels like an artificial limitation, because there's little reason for it to really fail. Currently, there are two things that require `numpy` and `scipy`:  `compas.geometry.algorithms.hull_numpy` and `compas.geometry.algorithms.bbox_numpy`. Both have their pure-python counterparts so it is not really required that the entire `compas.geometry` fails to import.

If possible, it would be preferable to keep these and all other imports that have pure-python counterparts, as optionals, i.e. they `try..except` the external dependency, and if not available, they don't raise an `ImportError`, regardless of Python runtime.

**Comment by tomvanmele** [comment]
no they shouldn't. working on removing that side effect.
should go away when all numerical solvers and methods have their own dedicated package as with DR...
