### ISSUE TITLE
Plane.is_parallel wrong result as given in the documentation

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas#1229]
**Describe the bug**
In the documentation of the example code.
The result after running the method is False (latest compas2 from github.)

<img width="670" alt="image" src="https://github.com/compas-dev/compas/assets/18013985/6332a034-a03a-44a3-9116-e53ea78d9c44">
<img width="761" alt="image" src="https://github.com/compas-dev/compas/assets/18013985/a54ec908-986e-4057-b1a9-ff9c0ad4b083">

This method:
https://github.com/compas-dev/compas/blob/main/src/compas/geometry/plane.py#L354

I think, instead of this:
`return abs(self.normal.dot(other.normal)) == 1 - tol`
it has to be:
`return abs(self.frame.zaxis.dot(frame.zaxis)) >= 1 - tol`

**To Reproduce**
```
    plane1 = Plane.worldXY()
    plane2 = Plane([1.0, 1.0, 1.0], [0.0, 0.0, 1.0])
    result = plane1.is_parallel(plane2)
    print(result)
```
prints False

**Expected behavior**
prints True

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Win
 - Python version [e.g. 2.7] - 3.11.6
 - Python package manager - conda

**Comment by tomvanmele** [comment]
yes, the implementation is indeed wrong. will fix...
thanks!

**Comment by tomvanmele** [comment]
will change to `abs(self.normal.dot(other.normal)) - 1 < tol`

**Comment by jf---** [comment]
@tomvanmele I think you've addressed this in the `compas.tolerance` refactor?

**Comment by tomvanmele** [comment]
yes indeed
