### ISSUE TITLE
bbox.py bug

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#123]
**change**
x, y = zip(*points)[:2]
**to**
points=[point[:2] for point in points]
x, y = zip(*points)

**Comment by tomvanmele** [comment]
because the first version is less efficient? it basically does 

```python
result = zip(*points)
x, y = result[:2]
```

**Comment by tkmmark** [comment]
TypeError: 'zip' object is not subscriptable

**Comment by romanarust** [comment]
`x, y = list(zip(*points))[:2]`

Because zip returns zip object in python 3, needs to be converted to a list.

**Comment by tkmmark** [comment]
Yes, that is the point.  Thank you for writing it more efficiently.

**Comment by gonzalocasas** [comment]
For these cases, it'd be ideal to add a unit test to make sure we don't introduce regressions down the road.

I added one on `develop` branch at https://github.com/compas-dev/compas/commit/ed598f7aa4b7ea06663ae0dee5706eb39b731b37 and fixed the implementation using `islice`. 

Wrapping it in a `list` also works of course, but `islice` is a tad faster. I just timed it with `timeit` on 3 million iterations, and it averages at `islice=7.5sec` vs `list=8.1sec`.

**Comment by tkmmark** [comment]
unit test is a great idea!

**Comment by tkmmark** [comment]
Unit testing sounds like a great idea!

**Comment by brgcode** [comment]
okay, solved!

will keep this to have a central location to report similar issues...
