### ISSUE TITLE
spelling consistencies

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#127]
Example:

**(1)**
def **normalize**_vector(vector):
    """**Normalise** a given vector.
(notice that the method name and the description use different English spelling)

**(2)**
some methods use **-or**: eg: color
other methods use **-our**: eg: neighbour

-recommend switching entirely to British English

**Comment by tomvanmele** [comment]
will do

**Comment by tomvanmele** [comment]
but not now, because it was not as easy as i thought :)

**Comment by tkmmark** [comment]
no worries, not urgent at all.

**Comment by gonzalocasas** [comment]
> -recommend switching entirely to British English

Maybe I'm biased, but I would find it awkward for an API to be in british English; I am not sure if there's a way to determine which is more common. Checking Rhino and Blender APIs quickly, it does feel like they use US English. The .NET Framework certainly uses US English. Python std lib uses mostly US English I believe, although I'm not 100% certain, but a search on the docs doesn't yield many british terms.

**Comment by tomvanmele** [comment]
initially i thought this was a good idea, but after trying to implement it i realised it indeed creates a number of counter-intuitive situations. perhaps we just need to go for consistent US english?

**Comment by tkmmark** [comment]
_Caption:_ **Where Each Variation Is Taught**
![image](https://user-images.githubusercontent.com/9421670/44289994-f41a3900-a276-11e8-8881-225325c01406.png)

**Comment by gonzalocasas** [comment]
A map is not really an accurate indicator of the preferred style of an API ;)

I just checked, and [PEP-0008](https://www.python.org/dev/peps/pep-0008/#comments) actually indicates US English because it recommends a famous US-English writing style guide:

 > When writing English, follow [Strunk and White](https://en.wikipedia.org/wiki/The_Elements_of_Style)

The remark is for comments, but since consistency is the keyword here, it goes without saying that code should adhere to the same convention.

**Comment by tomvanmele** [comment]
i think that is a convincing argument, because we try to stick to the default python conventions in every other aspect of the framework as well.

by the way:
https://en.wikisource.org/wiki/The_Elements_of_Style
https://en.wikipedia.org/wiki/The_Elements_of_Programming_Style

**Comment by tkmmark** [comment]
Yes, yes.  The convention of the API is a valid and irrefutable point... 
When I suggested British English, I was thinking of the variant that is more widely used in the world and in Europe, which appears appropriate for a group as international and as European as BRG... but screw population, let's switch to US 'English' then.

**Comment by tomvanmele** [comment]
the opinion of SO users:

https://stackoverflow.com/questions/157807/gb-english-or-us-english

**Comment by tkmmark** [comment]
Yes, I read that too.
But is the issue closed?
Has everything switched to US English?
