### ISSUE TITLE
draw_faces not show working

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas#1277]
Somehow `draw_faces` of `compas_rhino.scene.MeshObject`does not work, could you help me to look at the reason when you have a chance? Thanks @tomvanmele !
```python
from compas.datastructures import Mesh
from compas.scene import Scene


mesh = Mesh.from_polyhedron(8)

scene = Scene()

scene.clear()

meshObj = scene.add(mesh)
guids = meshObj.draw_faces(faces=[0, 1, 2])
print(guids)
```

When I run this script, the doc objects are successfully created with guids, but nothing is showing on screen. Meanwhile `draw_vertices` and `draw_edges` works as expected.

**Comment by tomvanmele** [comment]
you have to call `scene.draw()` to trigger the redraw of Rhino
