### ISSUE TITLE
introducing compas.geometry.symmetry

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#128]
-Takes any topology data structures (mesh, network, etc)
-Identify and output (A) all reflectional axes and (B) corresponding symmetrical pairing of vertices without the need for user's guidance
-O(n) complexity using a string-matching-based approach inspired by [1] that has been adapted here to work with more highly connected graphs.

![image](https://user-images.githubusercontent.com/9421670/44024761-8c164d3e-9eee-11e8-9c94-a2bce162f332.png)

[1] https://www.cs.princeton.edu/courses/archive/fall03/cs597D/lectures/symmetry.pdf

**Comment by tomvanmele** [comment]
hi mark,

this oesn't really seem like an *issue*.
could you move it to the forum where we can have a discussion about it...

thanks

**Comment by tkmmark** [comment]
Okay! I was advised that comments re: new features or features enhancements are posted here, and that the forum was reserved for questions about use.  In any case, I'll place this there then.
