### ISSUE TITLE
Transformations with objects/lists in ipy

### ISSUE THREAD

**Issue by romanarust** [compas-dev/compas#132]
The following throws an error in ironpython 2.7

```
from compas.geometry.xforms import Rotation
from compas.geometry import Point

R = Rotation.from_axis_and_angle([4,5,6], 7, point=[1,1,1])
p = Point(3,4,5)

p.transform(R)
```

Runtime error (ArgumentTypeException): zip() argument after * must be a sequence, not Object_1$1

Suggested solution: fix with list conversion

**Comment by tomvanmele** [comment]
added an explicit conversion in ``transpose_matrix`` and ``multiply_matrices``, but will probably need to do this in quite a few more places. will look for those during the update...
