### ISSUE TITLE
Geometric Key still uses compas.PRECISION

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas#1331]

**Comment by jf---** [comment]
@Licini can you pinpoint to a precise line of code perhaps?

**Comment by tomvanmele** [comment]
`compas.utilities.maps.geometric_key`

it should just be removed....

**Comment by tomvanmele** [comment]
as far as i can tell, they have been replaced by `compas.tolerance.TOL.geometric_key` everywhere.

@gonzalocasas remove?

**Comment by gonzalocasas** [comment]
Yep, I think so. Ideally "(only) one way to do things"

**Comment by Licini** [comment]
#1337

**Comment by Licini** [comment]
> @Licini can you pinpoint to a precise line of code perhaps?

It was this line https://github.com/compas-dev/compas/blob/4aff0800d2d6fcb960d48a43fbf5b497472d890d/src/compas/utilities/maps.py#L41

And now being removed at #1337
