### ISSUE TITLE
RobotModel SceneObject with Python3 in Rhino8 

### ISSUE THREAD

**Issue by gidodielemans** [compas-dev/compas#1355]
**Describe the bug**
Robot visualization not possible with Python3 in Rhino8

**To Reproduce**

```
from compas_robots.ghpython.scene import RobotModelObject
Load URDF from ROS

robot = ros_client.load_robot(
            load_geometry=True, 
            urdf_param_name= '/robot_description,
            srdf_param_name= '/robot_description_semantic')
robot.scene_object = RobotModelObject(robot.model)`
```

**Expected behavior**
A RobotModelObject for visualization is attached to the Robot object

**Error messages**
No scene object is registered for this data type: <type 'compas_robots.robot.model.RobotModel'>
No module named System.Array

**Desktop (please complete the following information):**
 - OS: Windows
 - Python 3.9.10
 - Python package manager Rhino (.rhinocode/py3.9-rh8)

**Comment by gidodielemans** [comment]
#1356 Here an attempt on a fix for the System module incompatibility

**Comment by tomvanmele** [comment]
hi, i think this is meant for `compas_robots`. there is no `RobotModelObject` in `compas` itself...

**Comment by tomvanmele** [comment]
yes, there are quite a few of these `System` problem in `compas_ghpython` in Rhino 8. thanks for the fix. will have a look...

**Comment by gidodielemans** [comment]
Related pull request in compas_robots https://github.com/compas-dev/compas_robots/pull/16
