### ISSUE TITLE
typo in cpython doc

### ISSUE THREAD

**Issue by worbit** [compas-dev/compas#137]
in the documentation about cpython [here](https://compas-dev.github.io/main/notes/cpython.html), there is a typo in the example on [line 125](https://github.com/compas-dev/main/blob/master/notes/cpython.html#L125): it says `artiat` instead of `artist`.
but the line should be reconsidered anyway, as it throws the following error:
`'MeshArtist' object has no attribute 'update'`

and my suggestion for line 16, which currently reads:
`xyz, q, f, l, r = XFunc('compas.numerical.fd_numpy')(vertices, edges, fixed, q, loads)`
would be to write it separate for more clarity, as on [this page](https://compas-dev.github.io/main/reference/generated/compas.utilities.XFunc.html), namely:
`fd_numpy = XFunc('compas.numerical.fd_numpy')`
`xyz, q, f, l, r = fd_numpy(vertices, edges, fixed, q, loads)`

**Comment by tomvanmele** [comment]
the typos were fixed, but the examples are temporarily removed from the list while it is being updated....
