### ISSUE TITLE
Mesh vertex indices of face are not always unique

### ISSUE THREAD

**Issue by romanarust** [compas-dev/compas#144]
I am loading an obj file into a `compas.Mesh` and found out that the vertex indices of some faces are not always unique. The obj file should be ok. 

Here is the python and the obj file to reproduce:
[https://gist.github.com/romanarust/9869828d880f2091fe95d33503caba27](https://gist.github.com/romanarust/9869828d880f2091fe95d33503caba27)

**Comment by gonzalocasas** [comment]
@romanarust please review my proposed fix ☝️  ;)

**Comment by romanarust** [comment]
Yes, great!
using `OBJ(file, precision='6f')` fixed it for meshes that are in meters
Thank you @gonzalocasas
