### ISSUE TITLE
Reconsider file metadata convention

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#147]
Currently, there's the convention of starting every single file in the framework with a metadata block like this one:
```python
__author__    = ['xxx', ]
__copyright__ = 'Copyright 201x - xxx'
__license__   = 'MIT License'
__email__     = 'xx@xx.xx'
````

The info is however highly redundant. Git itself holds proper history about how did what and when, the license field is just redundant for no reason, and the copyright field is mostly outdated on half the files by now, and would require manual caring (or scripted yearly updates at best) to be kept in sync.

I would suggest getting rid of them globally, and relying only on top level package metadata fields, and git history for understanding contribution.

**Comment by tomvanmele** [comment]
alright, making the change now.
added a CONTRIBUTORS file where people can be listed or list themselves.
can you add the GKR people there?

**Comment by gonzalocasas** [comment]
done!
