### ISSUE TITLE
Add install instructions for Blender on Mac

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#154]
re: https://compas-dev.github.io/main/environments/blender.html

I added the Windows install procedure, but I don't have a Mac version of Blender around. However, the changes between the two should be minimal, only update to bash's syntax and install locations (at least according [to the official Blender docs](https://docs.blender.org/api/blender_python_api_current/info_tips_and_tricks.html#bundled-python-extensions)).

**Comment by tomvanmele** [comment]
should be solved
