### ISSUE TITLE
Examples using MeshConduit not working

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#161]
It seems the `MeshConduit` is no longer available, or at least, no longer named `MeshConduit` so the remeshing examples don't work.

Was the conduit removed intentionally? If so, what would be the new way of doing the same thing?

**Comment by tomvanmele** [comment]
i removed the mesh conduit for now because it essentially does the same as a lines conduit.

rhino 6 seems to have an actual conduit for meshes, so i will add a conditional implementation to support direct mesh conduit drawing soon. 

will update the examples accordingly...

**Comment by gonzalocasas** [comment]
👍

**Comment by tomvanmele** [comment]
added the mesh conduit again and updated the examples
