### ISSUE TITLE
intersection_segment_segment_xy

### ISSUE THREAD

**Issue by salmamzfr** [compas-dev/compas#176]
After I updated COMPAS to the latest version yesterday, the intersection_segment_segment_xy (also intersection_line_line_xy) does not seem to function correctly anymore.  For example for the lines ((247.0, 189.0), (247.0, 188.0)) and ((246.0, 189.0), (248.0, 189.0)), the function returns None.

Also, sometimes when I change the order of points for one line in the input, the function output changes from an intersection point to None.  For example for ((248.0, 188.0), (247.0, 190.0)) and ((248.0, 188.0), (249.0, 188.0)) returns (248.0, 188.0), but for ((247.0, 190.0), (248.0, 188.0)) and ((248.0, 188.0), (249.0, 188.0)) returns None!

**Comment by tomvanmele** [comment]
thanks for reporting. having a look now...

**Comment by Rippmann** [comment]
I couldn't reproduce the error with the given points above. But something is indeed not working.

e.g. line pair:

([-18.05105004113592, -20.221692727960868, 0.0], [-28.056658399351893, -2.115065342520583, 0.0], [-14.419906050317167, -18.793313906826114, 0.0], [-13.313163253090753, -10.448679242591494, 1.9865751254080228])

also return None so ->"parallel" which is clearly wrong.

here is an example from stackoverflow that was reported to be working, robust and fast. Will check asap...

def line(p1, p2):
    A = (p1[1] - p2[1])
    B = (p2[0] - p1[0])
    C = (p1[0]*p2[1] - p2[0]*p1[1])
    return A, B, -C

def intersection(L1, L2):
    D  = L1[0] * L2[1] - L1[1] * L2[0]
    Dx = L1[2] * L2[1] - L1[1] * L2[2]
    Dy = L1[0] * L2[2] - L1[2] * L2[0]
    if D != 0:
        x = Dx / D
        y = Dy / D
        return x,y
    else:
        return False

**Comment by tomvanmele** [comment]
that is exactly what we implemented (albeit slightly reformulated).
however, we use a tolerance value instead of checking for `d` being zero.
this always fails when d is negative.
the function seems to work correctly if i compare the absolute value of `d` with the tolerance...

**Comment by tomvanmele** [comment]
should be solved in `3f6fac8`
please check and let me know, so i can close the issue...

**Comment by Rippmann** [comment]
It now works as intended. I tested it on a wide range of inputs. No errors.
