### ISSUE TITLE
Question:Mesh.halfedge for triangulated meshes  or ngon-meshes?

### ISSUE THREAD

**Issue by arch-tu** [compas-dev/compas#177]
is the ":Mesh.halfedge" for triangulated meshes  or ngon-meshes?, i have test it in rhino sucessfully,however, i cannot sure the out parameters,could you show the algorithm or script of the "Mesh.halfedge"?
thanks

**Comment by tomvanmele** [comment]
hi,

this sounds like something for the forum rather than the issue tracker.
could you re-post there (https://forum.compas-framework.org/)?

thanks

**Comment by arch-tu** [comment]
ok,
thanks for your reply~
