### ISSUE TITLE
LocalPackageMeshLoader for urdfs based on multiple packages

### ISSUE THREAD

**Issue by romanarust** [compas-dev/compas#181]
LocalPackageMeshLoader has both path and support_package attributes. Using only one support_package is not ideal if a urdf contains mesh urls in different packages. Suggest to remove support_package and to change self.schema_prefix to "package://".

**Comment by gonzalocasas** [comment]
The idea is that each instance of a loader takes care of only one thing (i.e. one package). The `load_geometry` function takes `n` loaders, so, it's easy to pass two or three if your urdf contains meshes from multiple packages (even of multiple sources, some might be github, some local, some ROS File Server).

**Comment by romanarust** [comment]
Ok, thanks a lot for clarification!
