### ISSUE TITLE
Removed vertex descriptors from Mesh

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#184]
On commit 6eb076a928f1ec6b4a6b6c9d6140f321d7a2e628 , the `VertexCoordinatesDescriptors` mixin was removed from `Mesh`, but it is not clear if the functionality was replaced by anything else. Also, the commit message doesn't seem to indicate the removal was really intended. Is there a new recommended way of getting things like `mesh.xyz`?

**Comment by tomvanmele** [comment]
```python
xyz = mesh.get_vertices_attributes('xyz')
```
