### ISSUE TITLE
Rhino xfunc throws an unicode error on some machines

### ISSUE THREAD

**Issue by tmsmendez** [compas-dev/compas#192]
The rhino version of the xfunc throws an error with any type of external function:
"SyntaxError:(unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX excape". 

This is the case only in a couple of machines (Francesco and Hao). The "non-rhino" xfunc version works.

**Comment by tomvanmele** [comment]
i made a small change to the rhino version. can you test?

**Comment by tomvanmele** [comment]
okay, seems related to the presence of unescaped backslashes in rhino-installed versions of COMPAS. should be fixed now...
