### ISSUE TITLE
Face modifications

### ISSUE THREAD

**Issue by robin-oval** [compas-dev/compas#20]
Functions to modify the vertices of a face ([a, b, c, d] -> [a, b, c, e] or [a, b, c, d] -> [a, b, c, d, e] for instance) that combines delete_face and add_face or that modifies directly the face vertices while updating the halfedges.

**Comment by tomvanmele** [comment]
has this already been addressed?

**Comment by robin-oval** [comment]
I'll make a PR for this soon.
