### ISSUE TITLE
center_of_mass_polygon 

### ISSUE THREAD

**Issue by anjalimehrotra** [compas-dev/compas#201]
center_of_mass_polygon gives an incorrect answer when applied to a simple triangle

pts = [(0,0,0),(1,0,0),(0,10,0)]
center_of_mass_polygon(pts)
(0.26246890528022254, 4.7624689052802225, 0.0)

**Comment by tomvanmele** [comment]
what is it supposed to be?

```python
[0.333, 3.333, 0.0]
```

**Comment by anjalimehrotra** [comment]
It's supposed to be [0.333, 3.333, 0.0], but for some reason when I run the code it gives me [0.26246890528022254, 4.7624689052802225, 0.0]

Thanks!

**Comment by tomvanmele** [comment]
this should be fixed now (fb280d9), please check.

**Comment by tomvanmele** [comment]
there is still the question what the centroid of the polygon surface should be if there are overlaps, but i will deal with that at a later time...
