### ISSUE TITLE
Online documentation returns HTML dump

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#204]
compas version 0.3.4
Searching for "point", returns HTML dumps of all matched pages.

![screenshot 2018-11-22 at 19 59 32](https://user-images.githubusercontent.com/38357732/48946810-2fd83500-ef2f-11e8-8d19-e5c1fb0b84a4.png)

**Comment by tomvanmele** [comment]
thanks for the reminder :)
the search function is indeed not yet working properly, but will be fixed in the next release (0.4.0)

**Comment by tomvanmele** [comment]
solved
