### ISSUE TITLE
'Point' object has no attribute 'x'

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#205]
When I'm trying to create a compas Point  I get the following error:

> Message: 'Point' object has no attribute 'x'
>
>Traceback:
>  line 99, in \_\_init\_\_, "/Users/axydis/PROJECTS/python/compas-dev/src/compas/geometry/objects/point.py"

```
from compas.geometry import Point
p = Point(1,2,5)
```

compas 0.3.4
Atom 1.32.2
Mac 10.14
Rhino 5.5.2

**Comment by Achillx** [comment]
After restarting both Rhino and Atom I have no error!
I do not know why.

I'll let you know if I figure out what triggers it.

**Comment by tomvanmele** [comment]
please do, because that shouldn't happen :)

**Comment by gonzalocasas** [comment]
It could be caused by a script context change. The find_object method is
cached on module-load time and perhaps it's invalid later on if the script
context changes (e.g. if Grasshopper changes it)

**Comment by Achillx** [comment]
I was not using grasshopper.

**Comment by tomvanmele** [comment]
are you sure? we won't tell anyone if you were ... :)

**Comment by tomvanmele** [comment]
progress?

**Comment by Achillx** [comment]
No, I haven’t being able to reproduce it.
But something similar, that also got fixed by restarting Rhino was when rhino artist stoped drawing edges and vertices, was not cleaning the layer, but it was drawing faces!

**Comment by tomvanmele** [comment]
there is an issue open about that one: #185 
but i don't think you have to restart Rhino to fix it, just reset the script engine...

**Comment by tomvanmele** [comment]
it seems to be related to the garbage collection of objects in IronPython, which would explain why it does not happen with the draw functions and only with the artist objects...

**Comment by andrewliew** [comment]
Closing, as it appears the error is not being reproduced, good!
