### ISSUE TITLE
Delanuay triangulation wrong result

### ISSUE THREAD

**Issue by tmsmendez** [compas-dev/compas#206]
Some geometries produce wrong results when using the Delanuay triangulation (or mesh from points) functions. For example, this code:

```python
from compas.datastructures import Mesh
from compas.plotters import MeshPlotter

pl = [[2.994817685045075, 10.855606612493078, 0.0],
      [4.185204599300653, 9.527867361977242, 0.0],
      [4.414125159734419, 10.718254276232818, 0.0],
      [5.925000858597267, 9.344730913630228, 0.0],
      [8.900968144236211, 10.809822500406325, 0.0],
      [9.496161601363999, 8.566401008155429, 0.0],
      [7.710581229980631, 7.9254234389408875, 0.0],
      [7.847933566240888, 6.414547740078039, 0.0],
      [3.9104999267801377, 4.9036720412151915, 0.0],
      [5.2909301507195865, 6.342692886748852, 0.0]]

mesh = Mesh.from_points(pl, boundary=None, holes=None)

plotter = MeshPlotter(mesh, figsize=(10, 6))

plotter.draw_vertices(text='key', radius=0.2, picker=10)

plotter.draw_edges()
plotter.draw_faces()
plotter.show()
```

Produces this mesh:
![meshplotter](https://user-images.githubusercontent.com/31008721/49075896-10475200-f238-11e8-84fb-b0e9c3301764.png)

Missing the edge shown in green.

**Comment by tomvanmele** [comment]
why should the green edge be there?
result looks correct to me...

**Comment by Rippmann** [comment]
Yes, that example is confusing. It is indeed the correct delaunay triangulation for the given set of points. The problem starts when you give it the boundary vertices [0, 4, 5, 7, 8, 9, 1, 0] I guess. @tmsmendez  can you not just include the example you showed me earlier last week? 
So, I think the delaunay algorithm is perfectly fine. I would be very surprised if not. But how boundaries and holes are enforced has some flaws that I need to weed out.

**Comment by tomvanmele** [comment]
but `boundary` and `holes` are `None` so the result is correct...

**Comment by tmsmendez** [comment]
It is the same example from last week. I indeed forgot to include the boundary, but this also does not return a correct result. So including the boundary:

```python
from compas.datastructures import Mesh
from compas.plotters import MeshPlotter

pl = [[2.994817685045075, 10.855606612493078, 0.0],
      [4.185204599300653, 9.527867361977242, 0.0],
      [4.414125159734419, 10.718254276232818, 0.0],
      [5.925000858597267, 9.344730913630228, 0.0],
      [8.900968144236211, 10.809822500406325, 0.0],
      [9.496161601363999, 8.566401008155429, 0.0],
      [7.710581229980631, 7.9254234389408875, 0.0],
      [7.847933566240888, 6.414547740078039, 0.0],
      [3.9104999267801377, 4.9036720412151915, 0.0],
      [5.2909301507195865, 6.342692886748852, 0.0]]

mesh = Mesh.from_points(pl, boundary=pl, holes=None)

plotter = MeshPlotter(mesh, figsize=(10, 6))

plotter.draw_vertices(text='key', radius=0.2, picker=10)

plotter.draw_edges()
plotter.draw_faces()
plotter.show()
```

I get this result:

<img width="556" alt="screenshot 2018-12-03 at 10 36 58" src="https://user-images.githubusercontent.com/31008721/49366013-83454280-f6e8-11e8-85b1-53976fefcefc.png">

The requested boundary in green.

**Comment by tomvanmele** [comment]
that makes sense.
the `from_points` constructor uses a delaunay triangulation of the given points as a starting point, which (in this case) looks like this:

![delaunay](https://user-images.githubusercontent.com/29653489/49366949-efc14100-f6ea-11e8-8ccf-6f36dbe35d59.png)

to create the boundary it will then check if the centroids of the faces are in the boundary polygon and remove those which are not.

here that means that `018` and `819` will be removed...

**Comment by tomvanmele** [comment]
so as a conclusion, the delaunays are correct. it is just very unclear what the purpose of `Mesh.from_points` is, and perhaps it should be removed...

**Comment by Rippmann** [comment]
If one wants to have a triangulation that fills up the entire polygon without leaving gaps (that's what I would expect as a user), one does need to do more than just deleting triangles based on the centroid. Either one implements a [CDT](https://link.springer.com/content/pdf/10.1007/BF01553881.pdf) and enforces the edges of the boundary (and holes) to always be part of the triangulation (demands edge-edge intersection checks), or one adds a sanitize function to fill possible "holes" (9,1,0 in this example). Maybe only called if there is a isolated vertex left [edit: no that would not be an appropriate check]?!  I will look into that. Let's also discuss this... sounds like an interesting algorithmic problem.

**Comment by Rippmann** [comment]
> 
> 
> so as a conclusion, the delaunays are correct. it is just very unclear what the purpose of `Mesh.from_points` is, and perhaps it should be removed...

The delaunay triangulation algorithm (compas python only) is working correctly but not the part of the function handling boundaries (and holes) for the aforementioned issues. So, I think the delaunay function needs some additions/improvements. I think mesh.from_points is a nice convenient function to construct a mesh. We just need to be clear in the docs what it is doing. It basically just wraps around the delauney function. So, maybe it should be called `Mesh.from_points_delaunay`

**Comment by tomvanmele** [comment]
solved!

![solved](https://user-images.githubusercontent.com/29653489/49371224-0c637600-f6f7-11e8-9048-57cb48b6c764.png)

**Comment by tomvanmele** [comment]
```bash
pip install triangle
```

```python
from compas.datastructures import Mesh
from compas.plotters import MeshPlotter
from triangle import triangulate

points = [
    [2.994817685045075, 10.855606612493078, 0.0],
    [4.185204599300653, 9.527867361977242, 0.0],
    [4.414125159734419, 10.718254276232818, 0.0],
    [5.925000858597267, 9.344730913630228, 0.0],
    [8.900968144236211, 10.809822500406325, 0.0],
    [9.496161601363999, 8.566401008155429, 0.0],
    [7.710581229980631, 7.9254234389408875, 0.0],
    [7.847933566240888, 6.414547740078039, 0.0],
    [3.9104999267801377, 4.9036720412151915, 0.0],
    [5.2909301507195865, 6.342692886748852, 0.0]
]

data = {
    'vertices': [point[0:2] for point in points],
    'segments': [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 0]]
}

res = triangulate(data, opts='p')

faces = res['triangles']
mesh = Mesh.from_vertices_and_faces(points, faces)

plotter = MeshPlotter(mesh)
plotter.draw_faces()
plotter.draw_vertices(text='key')
plotter.show()
```

will add `triangle` as a backend in the next release...

**Comment by tomvanmele** [comment]
```python
for fkey in list(mesh.faces()):
    vertices = mesh.face_vertices(fkey)
    v = len(vertices)
    if v > 3:
         key_index = {key: index for index, key in enumerate(vertices)}
         index_key = {index: key for key, index in key_index.items()}
         segments = [(key_index[u], key_index[v]) for u, v in mesh.face_halfedges(fkey)]
         xyz = mesh.face_coordinates(fkey)
         data = {'vertices': xyz, 'segments': segments}
         res = triangulate(data, opts='p')
         triangles = [(index_key[a], index_key[b], index_key[c]) for a, b, c in res['triangles']]
         del mesh.face[fkey]
         for tri in triangles:
             mesh.add_face(tri)
```

**Comment by tomvanmele** [comment]
support for constrained delaunay is now available through triangle
