### ISSUE TITLE
get vertices where the stored attribute is a list

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#207]
In `Mesh.vertices_where()` there is no way to filter vertices when you search for value and the attribute is of type list.

Perhaps adding the following? Works for me.

For the `if callable(method):`
```
if isinstance(val, list):
   if value not in val:
      is_match = False
      break
   break
```
and for its `else`
```
if isinstance(attr[name], list):
   if value not in attr[name]:
      is_match = False
      break
   break
```

**Comment by tomvanmele** [comment]
hi achillx,

are you using an installed version of COMPAS?
or a local copy?

in case of the latter, perhaps have a go at submitting a pull request.
please add at least two reviewers...

tom

**Comment by Achillx** [comment]
Hi tom,

I’ve cloned the master branch.

I will add the feature to edges and faces and submit a pull request.

Achilleas
