### ISSUE TITLE
Wrong example for trimesh_subdivide_loop

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#213]
**Describe the bug**
Is this the correct example for this functions?

**To Reproduce**
Goto:
[https://compas-dev.github.io/main/api/generated/compas.topology.trimesh_subdivide_loop.html?highlight=trimesh#compas.topology.trimesh_subdivide_loop](url)

**Comment by tomvanmele** [comment]
that example indeed makes no sense.
should be fixed in 6e5e0e3

**Comment by tomvanmele** [comment]
please check and close if okay...
