### ISSUE TITLE
planarity SyntaxError

### ISSUE THREAD

**Issue by andrewliew** [compas-dev/compas#22]
line 415
vectors = [[pos[n][axis] - pos[nbr][axis] for axis in 0, 1] for n in nbrs if n != key]
Returns SyntaxError under Python 3

**Comment by tomvanmele** [comment]
adding braces around the axis tuples solves the issue

`[[pos[n][axis] - pos[nbr][axis] for axis in (0, 1)] for n in nbrs if n != key]`
