### ISSUE TITLE
from_data; dict keys reshuffled

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#224]
When rebuilding a diagram using from_data, the dictionary keys in the new diagram for the various elements (vertex, faces, etc) are reshuffled.  This adds some additional mapping work when attempting to share data between different diagrams that are representing the same design (for instance, when working with RPC where serialisation and diagram reconstruction from serialised data is necessary). 
 Perhaps consider using an OrderedDict.

**Comment by tomvanmele** [comment]
can you give an example?

**Comment by tomvanmele** [comment]
this seems to be solved since 0abf421
