### ISSUE TITLE
Binary STL loading performance issues

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#230]
The performance is loading an STL binary mesh is pretty slow. The slowness seems to come from a few different factors, but mainly the `geometric_key` generation is very slow and the multiple small reads on the file are also slowing down the process (instead of a single longer read for the fixed size per triangle).

I'll send a PR with a proposal later today.

**Comment by gonzalocasas** [comment]
Being worked on on #231

**Comment by tomvanmele** [comment]
i merged #231 :)

**Comment by gonzalocasas** [comment]
@brgcode cool, thanks!

regarding the question you posted on the PR about suggesting geo_keys for post-processing, I've been testing a different way to generate geometric keys, it's quite faster than the current but it introduces a breaking change so I need to test quite a bit before sending a PR, but once I do, we can include things like this post-processing as an optional.
