### ISSUE TITLE
matplotlib broken on windows install of anaconda3

### ISSUE THREAD

**Issue by tomvanmele** [compas-dev/compas#233]
**Describe the bug**
Anaconda3 on windows ships with a broken version of Matplotlib.

**To Reproduce**
1. run any of the plotter modules as script.

**Desktop:**
 - OS: Windows
 - Python version: 3.x
 - Python package manager: conda

**Additional context**
Not sure about the specific version of Anaconda3.

**Comment by gonzalocasas** [comment]
@brgcode is this something we should report directly to the [matplotlib-feedstock](https://github.com/conda-forge/matplotlib-feedstock) repo? can it be reproduced without compas?

**Comment by tomvanmele** [comment]
will try to cook up an example...

**Comment by gonzalocasas** [comment]
Is the problem fixed now by any chance?
