### ISSUE TITLE
def get_points from layer 

### ISSUE THREAD

**Issue by mariklad** [compas-dev/compas#274]
method in compas_rhino.utilities get_points(var: layer) only works for None layer.

error returned: Message: LayerVisible() got an unexpected keyword argument 'force_visible'

Looking at the scr file replacing var: force_visible with forcevisible_or_donotpersist seems to solve the issue:
![image](https://user-images.githubusercontent.com/22766174/55144079-5a860480-5140-11e9-9f31-dd2fec732751.png)

**Comment by mariklad** [comment]
same for all get_lines, curves etc

**Comment by tomvanmele** [comment]
which version of Rhino is this?

**Comment by mariklad** [comment]
Rhino 6 SR12

**Comment by tomvanmele** [comment]
it might be something that was changed between versions. will have a look at the differences and add a fix to the next (patch) release...
