### ISSUE TITLE
Online documentation finds matches but returns nothing

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#279]
**Describe the bug**
Searching in the online documentation it finds matches but does not display them.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to compas-dev.github.io
2. Search for `cross product`
3. You(I) get `Search finished, found 8 page(s) matching the search query.`
4. But nothing is being displayed

**Expected behavior**
Display 8 pages that match the search query!

**Screenshoot**
![Screenshot 2019-04-15 at 17 22 58](https://user-images.githubusercontent.com/38357732/56145081-e2269c80-5fa3-11e9-9f65-02d4b9fcda7a.png)

**Desktop (please complete the following information):**
 - OS: [macOS 10.14.3 (18D42)]
 - Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by Achillx** [comment]
Sometimes it returns fewer that what was found and it might return duplicates.

![Screenshot 2019-04-18 at 10 56 21](https://user-images.githubusercontent.com/38357732/56349614-2ba40100-61c9-11e9-97fe-914c0d62660d.png)

**Comment by tomvanmele** [comment]
i do some filtering of the results after they are found. was a bit of a quick fix because the search function returns stuff that it shouldn't, but seems to result in the above behavior.

will be fixed when i roll out the new website...

**Comment by tomvanmele** [comment]
better now?
