### ISSUE TITLE
inherit attributes from previous mesh

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#288]
# Feature Request
It would be very useful if the `joined_mesh` from `compas.datastructures.mesh.join.meshes_join` would inherit all attributes from the original meshes.

## Details

**Is your feature request related to a problem? Please describe.**
I generate two meshes, both with many custom attributes in their faces and vertices. When I join them, the new mesh has none of them.

**Comment by jf---** [comment]
@tomvanmele its old and not specific

**Comment by gonzalocasas** [comment]
I think this is still relevant, joining two meshes should actually retain the custom attributes on them. We just need to define what's the behavior when both have the same attribute keys, but we could default to behave just like a dictionary's update() method.

I would propose to re-open
