### ISSUE TITLE
BrokenPipeError does not exists in IronPython

### ISSUE THREAD

**Issue by tomvanmele** [compas-dev/compas#289]
**Describe the bug**
The Proxy Server (RPC) throws a `BrokenPipeError` from time to time.

**To Reproduce**
1. Run an RPC with a relatively long running time
2. Exception ... BrokenPipeError

The error thrown on the IronPython side is a simple `Exception` and not a `BrokenPipeError` which is a Python 3+ thing.

**Expected behavior**
RPC should be able to throw something that can be recognised as a `BrokenPipeError` on the IronPython side.

**Comment by gonzalocasas** [comment]
Is this still current?

**Comment by tomvanmele** [comment]
nope
