### ISSUE TITLE
[Docs] OS-specific tabs for code snippets

### ISSUE THREAD

**Issue by yijiangh** [compas-dev/compas#296]
# Feature Request

It would be great to have an OS-specific tab for code snippets in the doc (especially for the installation):

![image](https://user-images.githubusercontent.com/11905844/59972889-647c9f80-9597-11e9-918f-a2e8eafd7c0e.png)

The snapshot above is taken from [https://sums-of-squares.github.io/sos/](https://sums-of-squares.github.io/sos/). This website is generated using Jekyll, the source code can be found [here](https://github.com/sums-of-squares/sos).

I don't know the difficulty of integrating this tab feature into our doc.

**Comment by tomvanmele** [comment]
something like this?
it is just a hard-coded one-off as a test...

https://compas-dev.github.io/main/gettingstarted/cad/blender.html
