### ISSUE TITLE
[compas_rhino] import compas error in Rhino under non-admin Windows account

### ISSUE THREAD

**Issue by yijiangh** [compas-dev/compas#297]
**Describe the bug**

I'm using compas with a **non-admin account** in Windows 10.  `compas` and `compas_rhino` are installed successfully in Anaconda prompt **with admin privilege**. But `compas` cannot be imported in Rhino 6.0.

**To Reproduce**

In Windows 10, I am using a non-admin account. The admin installed Rhino 6.0 for all users. Thus, both users have their own `C:\Users\<user name>\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)` directory. I have the password for the admin account, but I am trying to install and use compas in my own non-admin account.

I can install `compas_rhino` successfully by running the Anaconda prompt with admin privilege:
![image](https://user-images.githubusercontent.com/11905844/59973085-83306580-959a-11e9-8db5-ec2edc732680.png)

After restarting Rhino 6, I can't import `compas` in Rhino's python editor.
![image](https://user-images.githubusercontent.com/11905844/59973133-38631d80-959b-11e9-97d4-37594f037a6b.png)

**Potential cause for the bug**

The snapshot below shows the different results by running `whoami` in the Anaconda prompt with admin privilege (upper) and without (lower), under my non-admin Windows account.
![image](https://user-images.githubusercontent.com/11905844/59973021-a27ac300-9599-11e9-97a6-bd0af1aad523.png)

Installing `compas_rhino` requires admin privilege,  which will make the symlink set to the admin's Rhino IronPython but not the in the non-admin account's.

**Comment by yijiangh** [comment]
Commit https://github.com/compas-dev/compas/commit/f334785f92346ba9b630121acc3d485c6f7776c5 fixes this bug.

With https://github.com/compas-dev/compas/commit/f334785f92346ba9b630121acc3d485c6f7776c5, I can run Anaconda prompt **without admin privilege**, run `python -m compas_rhino.install` without any problem, and find `compas` successfully installed for Rhino IronPython:

![image](https://user-images.githubusercontent.com/11905844/59973304-67c75980-959e-11e9-9c83-aeefc87db7c1.png)

The only annoyance is that it will pop the privilege escalation dialog multiple times (once per package), which is acceptable for me at this moment.

@gonzalocasas @brgcode : With this, I will consider this bug fixed, but I will keep it open until commit f334785f92346ba9b630121acc3d485c6f7776c5 is merged.

**Comment by tomvanmele** [comment]
@gonzalocasas could this also be the root of the problems with RPC on some computers?

**Comment by tomvanmele** [comment]
@gonzalocasas the non-admin solution throws errors on RhinoMac. will document properly later today...

**Comment by gonzalocasas** [comment]
> the non-admin solution throws errors on RhinoMac. will document properly later today...

@brgcode could you post a stack trace or similar? I thought the change should not affect rhinomac at all, this only happens (or should happen) on the windows code path.

**Comment by gonzalocasas** [comment]
> @gonzalocasas could this also be the root of the problems with RPC on some computers?

I would not think of admin rights as the cause of RPC problems immediately, because RPC uses a non-privileged port, but on the hand, maybe there is something else that is failing on non-admin accounts during the rpc server start up.

**Comment by tomvanmele** [comment]
```
Message: libdl.so

Traceback:
  line 353, in __init__, "/Applications/Rhinoceros.app/Contents/Resources/ManagedPlugIns/RhinoDLR_Python.rhp/Lib/ctypes/__init__.py"
  line 441, in <module>, "/Applications/Rhinoceros.app/Contents/Resources/ManagedPlugIns/RhinoDLR_Python.rhp/Lib/ctypes/__init__.py"
  line 6, in <module>, "/Applications/Rhinoceros.app/Contents/Resources/ManagedPlugIns/RhinoDLR_Python.rhp/Lib/compas/_os.py"
  line 30, in <module>, "/Applications/Rhinoceros.app/Contents/Resources/ManagedPlugIns/RhinoDLR_Python.rhp/Lib/compas/__init__.py"
  line 7, in <module>, "/Users/vanmelet/Code/BlockResearchGroup/compas_hilo/scripts/fabric/02_assign-strips.py"
```

**Comment by gonzalocasas** [comment]
ah ok! I'll fix that
