### ISSUE TITLE
topology mesh examples point to wrong package

### ISSUE THREAD

**Issue by worbit** [compas-dev/compas#30]
The code example on the page [mesh_subdivide_catmullclark](https://compas-dev.github.io/main/reference/generated/compas.topology.mesh_subdivide_catmullclark.html) tries to import the `SubdMeshViewer` from the `compas.plotters` package, but this class is defined in the file `meshviewer.py` in the `viewers` package.
Maybe some disambiguation note about what are plotters and what are viewers and when to use which / search where would be helpful also.

**Comment by tomvanmele** [comment]
fixed in hotfix 0.1.0-subd_ck_example_imports.
merged into master and develop
