### ISSUE TITLE
[BUG] `frame.transform(T)` returns `None`

### ISSUE THREAD

**Issue by yijiangh** [compas-dev/compas#303]
**Describe the bug**
The following example ([doc link](https://compas-dev.github.io/main/api/generated/compas.geometry.Transformation.from_frame_to_frame.html#compas.geometry.Transformation.from_frame_to_frame)) on `Frame` transformation returns `None`:
```python
f1 = Frame([2, 2, 2], [0.12, 0.58, 0.81], [-0.80, 0.53, -0.26])
f2 = Frame([1, 1, 1], [0.68, 0.68, 0.27], [-0.67, 0.73, -0.15])
T = Transformation.from_frame_to_frame(f1, f2) # T is properly constructed
print(f1.transform(T))
# None
```
![image](https://user-images.githubusercontent.com/11905844/60806170-92aad380-a182-11e9-9d91-5cd5f7f3ee79.png)

**Setup:**
 - OS: Windows 10
 - Python version: 3.7
 - Python package manager: conda
 - compas version: `0.7.1`

**Comment by romanarust** [comment]
Thanks for pointing out! 
Note: `frame.transform(T)` should return `None`, because the `frame` itself gets modified. 
If you need a transformed copy of the frame, use `frame.transformed(T)`: this returns a new Frame.
