### ISSUE TITLE
[Docs] hyperlink to source code in doc

### ISSUE THREAD

**Issue by yijiangh** [compas-dev/compas#305]
# Feature Request

It would be nice if we can auto-generate a hyperlink to the source code in the compas doc. For example, see the `defined in xx` part in [tensorflow's documentation](https://www.tensorflow.org/api_docs/python/tf/add_check_numerics_ops). Links to source code really helps the users if the descriptions do not give enough information. I mentioned this in a previous issue #239 , trying to bring it up here again.

Right now, since the search function in compas's doc website cannot return all the desired search result, the way I search for functionalities within compas is to open compas's source code in an IDE, and do `search in the whole project`... (this is mentioned by #279)

**Comment by gonzalocasas** [comment]
@brgcode how about re-enabling `sphinx.ext.viewcode` on the docs?

**Comment by tomvanmele** [comment]
yes, will do...
