### ISSUE TITLE
[Docs] blender getting started

### ISSUE THREAD

**Issue by franaudo** [compas-dev/compas#306]
the environmental variable path in the getting started documentation for blender is not consistent throughout the document.

currently is _%PROGRAMFILES%\Blender Foundation\Blender\2.80_, but in the rest of the document this is the path to blender's python folder. it should be _%PROGRAMFILES%\Blender Foundation\Blender_ (without 2.80)

**Comment by tomvanmele** [comment]
should be fixed, please check...

**Comment by franaudo** [comment]
fixed!
