### ISSUE TITLE
Mesh.from_points() and delaunay_from_points() mismatch in Return and inputs

### ISSUE THREAD

**Issue by andrewliew** [compas-dev/compas#31]
Mesh.from_points() should return an object (Mesh datastructure) as in the docstring, however it calls delaunay_from_points() which currently says it returns an object, but returns mesh face indices instead. 

Also delaunay_from_points() is feeding in cls, which is not needed as a Mesh() is already instantiated in the function, so an argument error currently occurs.

Fix: is to remove cls from delaunay_from_points() as an input argument, and Return the mesh that is made inside delaunay_from_points().

**Comment by tomvanmele** [comment]
solved in hotfix 0.1.0-#31 and merged into master and develop...
