### ISSUE TITLE
meshes_weld precision in units rather string format

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#311]
# Feature Request

As a user, I want to input precision in project units rather in string format so that I can control how close the vertices should be to get welded.

**Comment by tomvanmele** [comment]
you mean something like
```python
compas.PRECISION = 0.001
```
instead of
```python
compas.PRECISION = '3f'
```

**Comment by Achillx** [comment]
Yes, but it doesn't have to be linked to `compas.PRECISION`. It can have its own precision, if that makes it easier.

**Comment by robin-oval** [comment]
and also allow something like
`compas.PRECISION = 10`

**Comment by tomvanmele** [comment]
no the problem is that it is more difficult to use precision in that format in the context of geometric maps

**Comment by tomvanmele** [comment]
anyway, i will try to see if i can implement something like this...

https://stackoverflow.com/questions/6189956/easy-way-of-finding-decimal-places

**Comment by tomvanmele** [comment]
@robin-oval 

> and also allow something like
> `compas.PRECISION = 10`

would that be `10` digits?

**Comment by robin-oval** [comment]
no, more the rounding precision: 11 becoming 10

**Comment by tomvanmele** [comment]
added a function for setting precision. for now it only handles floating point precision. for example

```python
compas.set_precision(0.0001)
# compas.PRECISION => '4f'
```
