### ISSUE TITLE
Viewer doesnt close properly for Mac users

### ISSUE THREAD

**Issue by andrewliew** [compas-dev/compas#33]
When using the compas Viewer, once finished, the window does not show red cross button and so cannot be easily closed. Need to resort to force closing of windows.

Confirmed problem for MacOS 10.13.2 and Python 2.7

**Comment by tomvanmele** [comment]
seems that on Mac, the GLUT main window cannot be closed, the application needs to be quit instead.
will check if i can work around this, but it will in any case be solved when making the switch to PySide based viewers...
