### ISSUE TITLE
Rhino dev/debug mechanism

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas#350]
When developing compas_rhino, each time after code updated, one has to quit Rhino completely and re-run compas installation for Rhino, and then re-open Rhino for the changes to take effect. 
Do we currently have any mechanism in place to help faster this process?

**Comment by tomvanmele** [comment]
the modules have to be reloaded, which you can do by restarting rhino or using the reload function in `compas_ghpython` (which should mybe be moved into `compas.utilities`). re-installing should never be necessary...

**Comment by gonzalocasas** [comment]
The function is already part of `compas_rhino`, I don't know if it's justified to move it even higher to core. I'd err on the side of nope
