### ISSUE TITLE
Example for XFunc and CPython in docs is using develop version of XFunc, not master

### ISSUE THREAD

**Issue by andrewliew** [compas-dev/compas#36]
A user identified the following error in the example https://compas-dev.github.io/main/tutorial/cpython.html:

"_I tried to run the example from tutorial CPython in Rhino that is on the
compas web page. When I copied the code in Rhino Python Editor it gave me
back Message: need more than 4 values to unpack. Is this example working at
your computer?_"

It looks like the example is using the newer **develop** XFunc format, where results are returned directly, expecting ``xyz, q, f, l, r`` in this case, rather than the **master** version which returns the results dictionary ``odict``.

**Comment by tomvanmele** [comment]
should be solved now. there is another bug in the example but will change that separately...
