### ISSUE TITLE
“network_find_crossings” provides repetitive edge pairs

### ISSUE THREAD

**Issue by salmamzfr** [compas-dev/compas#37]
“network_find_crossings” from compas.topology, returns repetitive edge pairs.

**Comment by tomvanmele** [comment]
hi,

could you send a sample file for which you found this to be the case?

thanks,
tom

**Comment by tomvanmele** [comment]
`network_find_crossings` now uses a set to check if a crossing has already been found in either direction...

**Comment by salmamzfr** [comment]
I was about to send you an example. Thanks.
