### ISSUE TITLE
Files created in ~ when running compas.gh_python on Mac

### ISSUE THREAD

**Issue by tetov** [compas-dev/compas#380]
**Describe the bug**
Files created in home directory when running compas.gh_python.

```
/Users/user/Layer Attributes.ghuser
/Users/user/Leader.ghuser
/Users/user/Get Rhino Groups.ghuser
/Users/user/Advanced Custom Preview.ghuser
/Users/user/Add Layout From Template.ghuser
/Users/user/Arc between 2 points..ghuser
/Users/user/Capture View.ghuser
/Users/user/Decunstuct Text 3D.ghuser
/Users/user/Get User Data.ghuser
/Users/user/Add New Layout.ghuser
/Users/user/Get Object Attributes.ghuser
/Users/user/Text Dot.ghuser
/Users/user/Text Contour.ghuser
/Users/user/Branch At Index.ghuser
/Users/user/Insert Block Instance.ghuser
/Users/user/Add User Data.ghuser
/Users/user/Advanced Group.ghuser
/Users/user/Text 3D Advanced.ghuser
/Users/user/Diameter Dimension.ghuser
/Users/user/Advanced Geometry Pipeline.ghuser
/Users/user/Bake Attributes.ghuser
/Users/user/Write To CSV File.ghuser
/Users/user/View Plane.ghuser
/Users/user/Advanced Ungroup.ghuser
/Users/user/Arrange Geometries.ghuser
/Users/user/Change Detail View Object.ghuser
/Users/user/Create Point Cloud.ghuser
/Users/user/Advanced Bake.ghuser
/Users/user/Dimensional Chain.ghuser
/Users/user/Create or Modify Block.ghuser
/Users/user/Delete Layout.ghuser
/Users/user/Hatch.ghuser
/Users/user/Angular Dimension.ghuser
/Users/user/Aligned Dimension.ghuser
/Users/user/Get Rhino Count.ghuser
/Users/user/Engrave Text.ghuser
/Users/user/BakeArrows.ghuser
/Users/user/View Attributes.ghuser
/Users/user/Deconstuct Dot.ghuser
/Users/user/Edit Dimension.ghuser
/Users/user/Unroll.ghuser
/Users/user/Plot Attributes.ghuser
```

**To Reproduce**
1. Open grasshopper
2. Create gh_python node
3. Run `import compas`
4. Look in home folder for files.

**Expected behavior**
No files created in home directory.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.5
 - Python version: IronPython 2.7
 - Rhino 6 for Mac (6.19.19298.01152, 2019-10-25)

**Comment by gonzalocasas** [comment]
I don't have a mac to test this, but I also don't see how this could be related to `compas`. As far as I know, we're not doing anything with ghuser files nor re-configuring any of the special folders when `compas_ghpython` is initialized.

**Comment by tetov** [comment]
Ok, me neither but I’d like to keep this open a bit longer so I have time to debug this on classmates laptop, if that’s ok.

Just to confirm, the files in the list above have no relation to compas?

**Comment by tetov** [comment]
The files correspond to nodes in FabTools. https://www.food4rhino.com/app/fabtools

I’m closing this since as you say it seems completely unrelated.
