### ISSUE TITLE
FrameArtist clears layer without being instructed to

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#391]
**Describe the bug**
When using FrameArtist multiple times in the same script, clear layer is called below the hood without user instruction.

I believe the problem is line 61 where the `clear = True` should not exist:

https://github.com/compas-dev/compas/blob/c0e1c7c76941f3c1428c9e573b18b32b210c666a/src/compas_rhino/artists/frameartist.py#L41-L63

**To Reproduce**
1. Call FrameArtist.draw() multiple times, only the last drawn result will remain.

**Expected behavior**
I expect to be able to call FrameArtist multiple times.

**Comment by Licini** [comment]
thx @yck011522 , will fix this bug in next release
