### ISSUE TITLE
"module has not object BoxArtist" or cannot "import BoxArtist from compas_rhino.artists"

### ISSUE THREAD

**Issue by inesariza** [compas-dev/compas#397]
Cannot import BoxArtist

should it be included in /artists __ init __ file?
https://github.com/compas-dev/compas/blob/master/src/compas_rhino/artists/__init__.py

**Comment by tomvanmele** [comment]
ideally, yes, but the `Shape` artists are not ready to be released yet. should have not been in the docs... did you find a reference to it somewhere else as well?

**Comment by tomvanmele** [comment]
by the way, the reason for this is that it is not clear if it makes sense to have a `Shape` artist at all, since all shapes would have to be visualised using a mesh. therefore, they would just provide a very thin wrapper around the `MeshArtist`.

**Comment by gonzalocasas** [comment]
I believe `Mesh.from_shape()` is included in the last release, so using the `MeshArtist` for this would be the way to go atm.
