### ISSUE TITLE
Evaluate (x ,y) for Meshes in compas

### ISSUE THREAD

**Issue by ricardoavelino** [compas-dev/compas#402]
# Feature Request

Would it be possible to evaluate a Mesh element in a given point (xi, yi) mapping the height z(xi, yi) of the mesh?

## Details

This feature would be very useful when one has a mesh representing a thrust network and has to evaluate the shape under a given configuration.

Three cases are possible for a given point (xi, yi), either it will not belong to the projection of the mesh in the x-y plane and in this case it could return None.

The point could lie in one of the edges of the mesh and in this case zi can be calculated as a linear combination of the heights of the vertices (u,v) of the edge.

The point would lie in one of the faces of the network, this would be hard to evaluate but it could also return simply a estimate of the heigh based on the height of the nodes belonging to that face.

This could also be seen as a sort of projection to a mesh and it could maybe be implemented for a given direction.

Is this feature possible to implement? If not, what would you suggest to be implemented on side to get the same/similar result?

Thanks.

**Comment by tomvanmele** [comment]
i will look into it.

in the meantime you can just use `scipy.interpolate.griddata`:

```python
heighfield = array(mesh.get_vertices_attributes('xyz'))
xy = ...
z = griddata(heighfield[:, :2], heightfield[:, 2], xy, method='linear', fill_value=0.0)
```
