### ISSUE TITLE
cmake issue during COMPAS session on 11.12

### ISSUE THREAD

**Issue by salmamzfr** [compas-dev/compas#423]
(example_package) C:\Users\msalma\Documents\example_cpp>pip install -e .
Obtaining file:///C:/Users/msalma/Documents/example_cpp
Requirement already satisfied: COMPAS in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from example-cpp==0.1.0) (0.11.4)
Requirement already satisfied: numba in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (0.46.0)
Requirement already satisfied: networkx in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (2.4)
Requirement already satisfied: sympy in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (1.4)
Requirement already satisfied: planarity in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (0.4.1)
Requirement already satisfied: scipy>=1.1 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (1.3.2)
Requirement already satisfied: pillow in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (6.2.1)
Requirement already satisfied: matplotlib<3.1,>=2.2; python_version >= "3.5" and sys_platform == "win32" in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (2.2.4)
Requirement already satisfied: numpy>=1.15.4 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (1.17.4)
Requirement already satisfied: cython in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from COMPAS->example-cpp==0.1.0) (0.29.14)
Requirement already satisfied: llvmlite>=0.30.0dev0 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from numba->COMPAS->example-cpp==0.1.0) (0.30.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from networkx->COMPAS->example-cpp==0.1.0) (4.4.1)
Requirement already satisfied: mpmath>=0.19 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from sympy->COMPAS->example-cpp==0.1.0) (1.1.0)
Requirement already satisfied: setuptools in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from planarity->COMPAS->example-cpp==0.1.0) (42.0.2.post20191201)
Requirement already satisfied: cycler>=0.10 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from matplotlib<3.1,>=2.2; python_version >= "3.5" and sys_platform == "win32"->COMPAS->example-cpp==0.1.0) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from matplotlib<3.1,>=2.2; python_version >= "3.5" and sys_platform == "win32"->COMPAS->example-cpp==0.1.0) (2.4.5)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from matplotlib<3.1,>=2.2; python_version >= "3.5" and sys_platform == "win32"->COMPAS->example-cpp==0.1.0) (2.8.1)
Requirement already satisfied: pytz in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from matplotlib<3.1,>=2.2; python_version >= "3.5" and sys_platform == "win32"->COMPAS->example-cpp==0.1.0) (2019.3)
Requirement already satisfied: six>=1.10 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from matplotlib<3.1,>=2.2; python_version >= "3.5" and sys_platform == "win32"->COMPAS->example-cpp==0.1.0) (1.13.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\msalma\appdata\local\continuum\anaconda3\envs\example_package\lib\site-packages (from matplotlib<3.1,>=2.2; python_version >= "3.5" and sys_platform == "win32"->COMPAS->example-cpp==0.1.0) (1.1.0)
Installing collected packages: example-cpp
  Running setup.py develop for example-cpp
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\msalma\\Documents\\example_cpp\\setup.py'"'"'; __file__='"'"'C:\\Users\\msalma\\Documents\\example_cpp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\msalma\Documents\example_cpp\
    Complete output (73 lines):
    running develop
    running egg_info
    writing src\example_cpp.egg-info\PKG-INFO
    writing dependency_links to src\example_cpp.egg-info\dependency_links.txt
    writing entry points to src\example_cpp.egg-info\entry_points.txt
    writing requirements to src\example_cpp.egg-info\requires.txt
    writing top-level names to src\example_cpp.egg-info\top_level.txt
    reading manifest file 'src\example_cpp.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching '.github'
    no previously-included directories found matching 'data'
    no previously-included directories found matching 'docs'
    no previously-included directories found matching 'docsource'
    no previously-included directories found matching 'examples'
    no previously-included directories found matching 'temp'
    no previously-included directories found matching 'tests'
    warning: no previously-included files found matching 'requirements-dev.txt'
    warning: no previously-included files found matching 'pytest.ini'
    warning: no previously-included files found matching '.bumpversion.cfg'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching 'tasks.py'
    warning: no previously-included files found matching 'CONTRIBUTING.md'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.nb[ic]' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    writing manifest file 'src\example_cpp.egg-info\SOURCES.txt'
    running build_ext
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:3 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/msalma/Documents/example_cpp/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\msalma\Documents\example_cpp\setup.py", line 128, in <module>
        cmdclass=dict(build_ext=CMakeBuild),
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\site-packages\setuptools\command\develop.py", line 38, in run
        self.install_for_development()
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\msalma\Documents\example_cpp\setup.py", line 47, in run
        self.build_extension(ext)
      File "C:\Users\msalma\Documents\example_cpp\setup.py", line 78, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\msalma\\Documents\\example_cpp', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\msalma\\Documents\\example_cpp\\src', '-DPYTHON_EXECUTABLE=C:\\Users\\msalma\\AppData\\Local\\Continuum\\anaconda3\\envs\\example_package\\python.exe', '-DCMAKE_INSTALL_RPATH=@loader_path', '-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON', '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\msalma\\Documents\\example_cpp\\src', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\msalma\AppData\Local\Continuum\anaconda3\envs\example_package\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\msalma\\Documents\\example_cpp\\setup.py'"'"'; __file__='"'"'C:\\Users\\msalma\\Documents\\example_cpp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by tomvanmele** [comment]
please repost on the relevant repo
