### ISSUE TITLE
missing examples in `compas.robots` Model

### ISSUE THREAD

**Issue by wenqian157** [compas-dev/compas#430]
`RobotModel`
`RobotModel.find_parent_joint`
`RobotModel.from_urdf_file`
`RobotModel.from_urdf_string`
`RobotModel.get_base_link_name`
`RobotModel.get_configurable_joint_names`
`RobotModel.get_configurable_joints`
`RobotModel.get_end_effector_link`
`RobotModel.get_end_effector_link_name`
`RobotModel.get_joint_by_name`
`RobotModel.get_joint_types`
`RobotModel.get_link_by_name`
`RobotModel.get_positions`
`RobotModel.iter_chain`
`RobotModel.iter_joint_chain`
`RobotModel.iter_joints`
`RobotModel.iter_link_chain`
`RobotModel.iter_links`
`RobotModel.load_geometry`
`RobotModel.scale`
`RobotModel.transformed_axes`
`RobotModel.transformed_frames`
`Joint.calculate_continous_transformation`
`Joint.calculate_fixed_transformation`
`Joint.calculate_floating_transformation`
`Joint.calculate_planar_transformation`
`Joint.calculate_prismatic_transformation`
`Joint.calculate_revolute_transformation`
`Joint.calculate_transformation`
`Joint.create`
`Joint.is_configurable`
`Joint.is_scalable`
`Joint.scale`
`Joint.transform`
`Link`

**Comment by romanarust** [comment]
closing this partly with b177a5e
`Joint.calculate_*` seem not necessary as these are internal methods and `Joint.is_configurable` and `Joint.is_configurable` don't need examples ;)
