### ISSUE TITLE
missing examples in `compas.robots` Joint

### ISSUE THREAD

**Issue by wenqian157** [compas-dev/compas#436]
`ParentLink`
`ChildLink`
`Calibration`
`Dynamics`
`Limit`
`Limit.scale`
`Axis`
`Axis.copy`
`Axis.transform`
`Axis.transformed`
`Mimic`
`SafetyController`

**Comment by gonzalocasas** [comment]
Since these classes are all intended to be used mostly from a URDF file, or via programmatically modeling a full robot, I don't think they need examples, so I will close this one for now.
