### ISSUE TITLE
missing examples in `compas.robots` Resources

### ISSUE THREAD

**Issue by wenqian157** [compas-dev/compas#438]
`AbstractMeshLoader`
`AbstractMeshLoader.can_load_mesh`
`AbstractMeshLoader.load_mesh`
`DefaultMeshLoader`
`DefaultMeshLoader.can_load_mesh`
`DefaultMeshLoader.load_mesh`
`GithubPackageMeshLoader`
`GithubPackageMeshLoader.build_url`
`GithubPackageMeshLoader.can_load_mesh`
`GithubPackageMeshLoader.load_mesh`
`GithubPackageMeshLoader.load_urdf`
`LocalPackageMeshLoader`
`LocalPackageMeshLoader.build_path`
`LocalPackageMeshLoader.can_load_mesh`
`LocalPackageMeshLoader.load_mesh`
`LocalPackageMeshLoader.load_urdf`

**Comment by gonzalocasas** [comment]
These examples are documented as top-level examples, not inlined in the functions: https://gramaziokohler.github.io/compas_fab/latest/examples/02_description_models.html
