### ISSUE TITLE
Lazy initialization of readers and parsers of file classes

### ISSUE THREAD

**Issue by beverlylytle** [compas-dev/compas#452]
Within the collection classes from the files module, some of the doc strings promise the possibility not only of reading certain file types, but also writing them.  The current structure of these classes requires reading a file on initialization.  However, it seems that a user might want to first create some variation on a compas data structure, say a list of meshes, and then write that list to an obj file.  The suggestion of this issue is to still initialize the file classes OBJ/STL/etc with a file path and a precision, but to initialize the associated readers and parsers lazily or when a to-be-introduced read method is called on the OBJ/STL/etc. instance.  Such a change would work well with the current plans for a glTF exporter.

**Comment by beverlylytle** [comment]
@brgcode  What do you think?

**Comment by tomvanmele** [comment]
agreed!

**Comment by tetov** [comment]
Seconded.

Writing files will be moved to the file modules (probably with a new parent class; base_writer) as per discussions with @brgcode and @gonzalocasas, which means the file modules will not only be used for reading. When writing is implemented in those modules lazy loading the reader and parser would be a good idea.

Edit: I should have been clearer, I'm talking about the current file modules except xml_ & urdf. I also reworded my comment a bit.

**Comment by tomvanmele** [comment]
can this be closed?

**Comment by beverlylytle** [comment]
Yes.
