### ISSUE TITLE
Support for Pyside and Python 3.6 until Pyside2 is available

### ISSUE THREAD

**Issue by andrewliew** [compas-dev/compas#47]
Given that Python 3.6 wheels are available for [Pyside](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyside), and that Pyside2 has no clear release date. Suggestion is to use Pyside instead for the current Viewer, and make available support for Pyside widgets in **compas** and then port over to Pyside2 later.

**Comment by tomvanmele** [comment]
it seems Pyside2 can now be installed quite easily with conda. therefore in the next release the viewers will be based on Pyside(2) and Vtk...
