### ISSUE TITLE
Add to_data() from_data() methods for RobotModel

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#483]
# Feature Request

As a user, I create my `RobotModel` using code, with Mesh attached to Links and Joints defined.

But I currently cannot serialize this and therefore I cannot save and load it from disk. I expect methods such as `from_data()` and `to_data()` to exist, as consistent with other compas classes.

This will also allow deep copies of the `RobotModel`, and subsequently `RobotModel.copy()`.

**Comment by tomvanmele** [comment]
@gonzalocasas could you have a look at this?

**Comment by gonzalocasas** [comment]
I take it into our backlog. However, to be honest, right now this does not have very high prio, so, it will be a while until we get to it.

**Comment by yck011522** [comment]
@gonzalocasas  Thanks for your honesty 😅
