### ISSUE TITLE
Add artist for RobotModel

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#484]
# Feature Request

As a user, I want artist that can visualize RobotModel.

## Details
The newly added RobotModel class is nice. But without artists that can paint it, there is nothing much I can do with it. 

In particular I'm interested in a ghpython artist implementation.

**Comment by tetov** [comment]
There is an artist with a ghpython implementation in compas_fab. See class  [Robot](https://gramaziokohler.github.io/compas_fab/latest/reference/generated/compas_fab.robots.Robot.html#compas_fab.robots.Robot) and the [ghpython artist](https://gramaziokohler.github.io/compas_fab/latest/reference/generated/compas_fab.ghpython.RobotArtist.html#compas_fab.ghpython.RobotArtist). 

The compas_fab class Robot is defined using a RobotModel, RobotSemantics (from compas_fab) and optionally an artist.
