### ISSUE TITLE
Error when installing compas from source

### ISSUE THREAD

**Issue by ricardoavelino** [compas-dev/compas#489]
When installing compas from source we get 2 known issues: 

- There is need to install cython "by hand"
- Microsoft Visual C++ Build Tools are missing, so this software has to be downloaded and installed manually.

Can this be automatically installed when we are doing the installation from source? Or can this be more explicitly explained in the documentation?

Thanks.

**Comment by gonzalocasas** [comment]
The automatic installation is the one based on conda, where these issues should not occur. A source install always implies a more involved process by definition.

These two issues you mention are already documented together with their solutions: https://compas-dev.github.io/main/gettingstarted/knownissues.html
