### ISSUE TITLE
Problem when pull from compas and file does not overwrite automatically (VSCode)

### ISSUE THREAD

**Issue by ricardoavelino** [compas-dev/compas#493]
**Describe the bug**
When I pull from the latest version of compas, the file compas_plotters/artists/__init__.py does not overwrite automatically, instead I have a error message in VSCode that asks me to accept the changes "again". The changes come after the line:

```
<<<<<<< HEAD (Current Change) 
=======
from compas.geometry import Ellipse
from compas.datastructures import Mesh
>>>>>>> 1309732c7e895e8614ac6dcb0b10360471d1ab06 (Incoming Change)
```

Below I send a screenshot of the error in VSCode. Of course, if I press "Accept Incoming Change" (as shown in the screenshot) it will accept the changes of the latest files but I do not understand what it does not do so automatically. Can someone help me understand why I get that?

**Screenshots**
![image](https://user-images.githubusercontent.com/36137188/76418045-3dbcfe00-639e-11ea-94d8-00f6b1ed9557.png)

**Desktop (please complete the following information):**
 - OS: Catlina 10.15.2 
 - Python 3.6.7
 - VSCode text editor with extensions recommended installed.
- compas installation executed from source with unreleased version

Thanks again!

**Comment by gonzalocasas** [comment]
You have a merge conflict. You need to accept the changes, ensure the file looks ok (no weird `<<<<` symbols anywhere), and then commit. Committing will effectively "confirm" the incoming changes already merged. I close this, as this is not a compas bug, but a git question, but you can keep posting here if you still faces issues with resolving it.
