### ISSUE TITLE
volmesh_from_polysurface

### ISSUE THREAD

**Issue by salmamzfr** [compas-dev/compas#495]
**Describe the bug**
tried this:

> from compas_rhino.geometry._constructors import volmesh
> import rhinoscriptsyntax as rs
> guids = rs.GetObject(“select a closed polysurface”, filter=rs.filter.polysurface)
> volmesh = volmesh.volmesh_from_polysurfaces(VolMesh, guids)

returns:

> Message: iteration over non-sequence of type Guid
> 
> Traceback:
> line 48, in volmesh_from_polysurfaces, “C:\Users\msalma\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\compas_rhino\geometry_constructors\volmesh.py”
> 

**To Reproduce**
1. Context [e.g. ST3, Rhino, Blender, ...]
2. Sample script
3. Sample data

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python version [3.7]
 - Python package manager [conda]

**Additional context**

**Comment by tomvanmele** [comment]
@juney-lee perhaps this can be addresses during the update of `compas_3gs`?

**Comment by tomvanmele** [comment]
looking a bit closer at the error, the problem might already be solved by wrapping the result from `GetObject` in a list. the function returns a single guid, whereas the volmesh constructor expects a list of guids...

something like this might work

```python
guid = rs.GetObject(“select a closed polysurface”, filter=rs.filter.polysurface)
guids = [guid]
```

**Comment by tomvanmele** [comment]
each polysurface in this list should be the b-rep of a cell in the volmesh. the volmesh constructor then uses the boundary loops of each of the polysurfaces to create the faces of the corresponding cell...

i think the data file `boxes.obj` is an example of correct input

**Comment by tomvanmele** [comment]
is this working now?

**Comment by tomvanmele** [comment]
@salmamzfr is this resolved?

**Comment by salmamzfr** [comment]
Yes it is! Although I don't seem to find any documents on "volmesh_from_polysurfaces" on the website! I don't remember where I found this function originally!

**Comment by salmamzfr** [comment]
Also after running this:

```
from compas_rhino.geometry._constructors import volmesh
import rhinoscriptsyntax as rs
guid = rs.GetObject(“select a closed polysurface”, filter=rs.filter.polysurface)
guids = [guid]
volmesh = volmesh.volmesh_from_polysurfaces(VolMesh, guids)
```

when I run 

`print volmesh`

I get this error: 

```
Message: 'VolMesh' object has no attribute 'edge'

Traceback:
  line 306, in data, "C:\Users\msalma\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\compas\datastructures\volmesh\volmesh.py"
  line 216, in __str__, "C:\Users\msalma\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\compas\datastructures\volmesh\volmesh.py"

```

**Comment by tomvanmele** [comment]
but until the print statement everything is fine?

**Comment by salmamzfr** [comment]
Yes!

**Comment by tomvanmele** [comment]
@brgcode

**Comment by tomvanmele** [comment]
volmesh has been completely restructured. this problem should no longer exist now...
