### ISSUE TITLE
Missing docs for compas.geometry.Vector

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#515]
# Feature Request

Is there a plan to also document `compas.geometry.Vector` ?

I notice this class exist in [code](https://github.com/compas-dev/compas/blob/master/src/compas/geometry/_primitives/vector.py) and I can also use it. But it is not in the [docs](https://compas-dev.github.io/main/api/compas.geometry.html).

Or is there a reason why this is not included?

**Comment by tomvanmele** [comment]
will be added

**Comment by tomvanmele** [comment]
this is now resolved, correct?

**Comment by tomvanmele** [comment]
@yck011522 can this be closed?

**Comment by yck011522** [comment]
Yep, this is fixed. Thanks.
