### ISSUE TITLE
devo_numpy import error in Rhino

### ISSUE THREAD

**Issue by tmsmendez** [compas-dev/compas#52]
When importing anything from `compas.numerical` in Rhino, an error is thrown saying `Numpy` could not be imported. It tracks down to the Differential Evolution importing its own plotter and the plotter imports `Numpy` without a try except. I like the idea of having the plotting be a kwarg in the optimisation function, but there is now a lot of stuff in `compas.numerical` that is `Numpy` free.

**Comment by andrewliew** [comment]
try except added to devo_numpy in develop branch
