### ISSUE TITLE
BaseReader should not use pathlib/pathlib2, pathlib2 not available in IronPython

### ISSUE THREAD

**Issue by tetov** [compas-dev/compas#529]
Did not realize this when I created BaseReader..

I'll submit a PR shortly to fix this. Need to restart the refactoring as well.

**Comment by tomvanmele** [comment]
perhaps wait with refactoring until we have had a discussion about it. the new version is 2x slower and consumes the same amount of memory, so perhaps it would for now be more useful to define interfaces for the reader, parser, and writer than providing a base implementation for those...

**Comment by tetov** [comment]
Ok, no problem!
