### ISSUE TITLE
Calculation of geodesic distances starting from many vertices

### ISSUE THREAD

**Issue by ioannaMitropoulou** [compas-dev/compas#538]
**Describe the bug**
I would like to report a problem I have with the heat geodesics calculation (compas.datastructures.mesh_geodesic_distances_numpy). When I calculate geodesic distances with one vertex as a start point, the result seems to be correct (though I haven't verified it). However, when I calculate with multiple start points, then the result is definitely wrong. (see screenshots below)

**To Reproduce**
I have created this simple example that illustrates the problem. You can download it here:
https://www.dropbox.com/sh/qg10kywmiugh52c/AADV7J0VQkB9hDmgoZ-pEZeza?dl=0
Run the code to see the distance gradient that is produced starting from multiple vertices.

**Expected behavior**
The correct gradient starting from all these vertices should be parallel to the boundary line.  As a comparison, I also attach images of the geodesic distances (again using the same heat algorithm), calculated in libigl, with the exact same inputs.  

**Screenshots**

**Compas**

Geodesic distances starting from one vertex. These seem to be correct. (starting vertex in blue)

![3b](https://user-images.githubusercontent.com/17250275/80957236-136a4880-8e03-11ea-92f6-dc356d2f7c4f.PNG)

Geodesic distances starting multiple vertices. These are wrong.  (starting vertices in blue)

![3a](https://user-images.githubusercontent.com/17250275/80957334-3e549c80-8e03-11ea-81da-7d7b76a992de.PNG)

**Libigl**
Geodesic distances starting from one vertex. (starting vertex in red)

![3d](https://user-images.githubusercontent.com/17250275/80957367-49a7c800-8e03-11ea-8eef-53b60027be2c.PNG)

Geodesic distances starting multiple vertices. (starting vertices in red)

![3c](https://user-images.githubusercontent.com/17250275/80957390-53313000-8e03-11ea-9069-2b9d637dce6a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version: 3.7.6
 - Python package manager: conda-forge

**Comment by tomvanmele** [comment]
with a value of 1000 for parameter m, the result is (almost) the same as the image from igl...

**Comment by ioannaMitropoulou** [comment]
Many thanks for the reply! Indeed you are right. I had not tried using such a high value for m, because in the heat geodesics paper a time step with m=1 is recommended. It says that higher values would create a smooth approximation of the geodesic distances.  But maybe this m=1000 just accounts for the different units? I will test it with m=1000 on more complex shapes and will let you know if I have more problems.

**Comment by tomvanmele** [comment]
in any case the exact method and the heat method of `libigl` are available through `compas_libigl`, which by the end of this week should be conda installable...

**Comment by ioannaMitropoulou** [comment]
Great, thanks for the info! On the same example, with m = 1000 and a some better coloring, I still see some problems in the resulting distances. 

![3e](https://user-images.githubusercontent.com/17250275/80967224-4407ad80-8e16-11ea-90fa-391f5fcc2fb6.PNG)
