### ISSUE TITLE
API search

### ISSUE THREAD

**Issue by KEERTHANAUDAY** [compas-dev/compas#539]
The compas Docs API search is down.
https://compas-dev.github.io/main/search.html?q=Mesh&check_keywords=yes&area=default#

**Comment by tomvanmele** [comment]
yes i know. and i can't figure out what is wrong :)

**Comment by tomvanmele** [comment]
did it still work recently?

**Comment by KEERTHANAUDAY** [comment]
Yes it works now

**Comment by tomvanmele** [comment]
thanks
