### ISSUE TITLE
[doc] documenting REPL example for `compas.rpc` and `compas.utilities.xfunc`

### ISSUE THREAD

**Issue by yijiangh** [compas-dev/compas#540]
# Feature Request

As a CPython package developer, I want to see a more elaborative example to demonstrate the develop/debug workflow ([REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop)) when using `GHPython` + `compas.rpc` as a frontend input engine for testing my external CPython package.

To demonstrate this workflow, several questions need to be addressed in the doc but currently missing:
1. how can I work in the `debug` (`-e`) mode, i.e. having the changes in script be reflected in the rpc function call?
2. how and where can I see the print outputs from the CPython side?
3. If the CPython side has `input` to block the process to enable us to inspect the printouts or the GUI visualization, how can we "press enter" with `rpc`?
4. we can only use `Xfunc` or `Rpc` for python **packages** that have been installed in the conda environment, right? Can we call a script directly? (I had this question while trying to developing a test script for you to play with...)

## Details

**Is your feature request related to a problem? Please describe.**
Let's ground the context on a specific example, all the tests below is performed with `compas 0.13.3`:

Let's say that I'm developing a force density method python package called `pyfdm` that has been installed to the compas conda environment by:
```
conda activate compas_env
# cd into pyfdm's dir
pip install -e .
# expose this package to compas_rhino
python -m compas_rhino.install -p pyfdm
```

Now, I want to draw the initial grid and indicate fixities in Rhino/GH, and test
my package by making a function call in my GHPython component:

```
from compas.rpc import Proxy
fdm_rpc = Proxy('pyfdm')
updated_grid_pts = fdm_rpc.compute_fdm(grid_pts, connectivity, fixities, ...)
```
### Q1: debug mode
Even though from above, I've `pip install`ed the `pyfdm` package with the `-e` option, I found that I need to restart the proxy as follows to let the change be reflected in the rpc call:

```
fdm_rpc.stop_server()
fdm_rpc.start_server()
```
Since this takes a bit of runtime to kill and restart the proxy, and also it sometimes kill the `compas_rpc start` process in the external commandline. I'm wondering if there is a more principled way to do this?

### Q2: direct prints?
I'm confused about how we can direct the `print` happening in the CPython side to a visible place (either GHPython's output panel or an externally launched command-line prompt).

Now, if I want to print out some information after I did some computation inside my `compute_fdm` function to help my debugging? How can I do that? Apparently the print does not show up in the GHPython component output panel.

I've tried the following process:
1. First, I run `compas_prc start`  in my command-line outside GH/Rhino
2. init the Proxy inside GHPython component
3. Expecting the print show up in the external command-line prompt... But I fail.

I remember in February this year I tried the same thing and it worked fine...

### Q3: `input`

If I have an `input` in some of the lines in the `compute_fdm` function, how can I work with it in `rpc`? 

In `xfunc` I know that I can specify `python=python` when creating the `XFunc` object, and press `Enter` in the launched external prompt like this:

![image](https://user-images.githubusercontent.com/11905844/81204397-26158680-8f97-11ea-837a-068be0917fee.png)

### Q4: can we invoke a script?

The final question is if we can run an external script just like `python <path_to_script>/py_script.py` in `rpc` or `xfunc`? 

If we can only work with installed package, then we should demonstrate how to create, install, and debug/develop a python package (and point to the [compas cookiecutter](https://github.com/compas-dev/cookiecutter-pypackage)).

**Comment by gonzalocasas** [comment]
@yijiangh would you say this is done? could we close it?

**Comment by yijiangh** [comment]
Yes! Great work, thank you all so much!
