### ISSUE TITLE
Add Documentation for compas.datastructures.meshes_join()

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#542]
# Feature Request

Can we have a function to join two Mesh.

## Details

I would like to combine two mesh (may or may not overlap) into one single Mesh object
Where:
new_mesh.vertices=mesh1.vertices+ mesh2.vertices (these Index are renumbered)
new_mesh.faces = mesh1.faces + **mesh2.faces (mapping to new indices)

This is more of a basic function and there are many uses. Perhaps should be implemented at Graph level, but I'm not sure.

**Additional context**
This is similar to the join function in Rhino.

**Comment by tomvanmele** [comment]
that function exists but i noticed it is not in the docs...
`compas.datastructures.meshes_join`

**Comment by yck011522** [comment]
Arh. Nice. Maybe add it to the docs?

**Comment by yck011522** [comment]
Fixed by #583
