### ISSUE TITLE
Add unweld option when exporting meshes in obj

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#555]
# Feature Request

When exporting a mesh to obj choose to have it unwelded or welded.

## Details

When quickly previewing welded meshes with mac's built-in preview, or when importing them in Rhino, they look horrendous!

Allow passing welded or unwelded to mesh exporter. `mesh.to_obj(welded=False)`

![weld_unweld](https://user-images.githubusercontent.com/38357732/83747377-d0e59700-a660-11ea-9539-fffed7031a3f.png)
Top 3 meshes are just imported and the bottom ones have been unwelded using Rhino's `Unweld` command.

![weld_unweld_02](https://user-images.githubusercontent.com/38357732/83747364-cdeaa680-a660-11ea-8286-ee44e5817e9a.png)
Here a closer look.

**Comment by tomvanmele** [comment]
will include in the next release...

**Comment by tomvanmele** [comment]
the latest dev version should have an unweld option.
please check...

**Comment by tomvanmele** [comment]
@Achillx ping?

**Comment by Achillx** [comment]
Sorry, I'm still working on an older version of compas.

- I made an environment with compas version 0.16.0-74777898
- Loaded a welded obj with `mesh.from_obj()`
- exported it again welded and unwelded

The unwelded version looks perfect!
