### ISSUE TITLE
mesh.key_index()  non_corresponding after mesh.to_data()

### ISSUE THREAD

**Issue by duchaoyu** [compas-dev/compas#557]
After writing the mesh (mesh1) data to data dictionary, and construcing a new mesh (mesh2) from this data dictionary, the order of dictionary keys changes. Thus, mesh1.key_index() is not the same as mesh2.key_index() 

Here's the vertice in mesh1:
```
    "vertex": {
        "0": {
            "x": -0.70710678118654768, 
            "y": 11.707106781186546, 
            "z": 0.0
        }, 
        "1": {
            "x": 0.0, 
            "y": 10.0, 
            "z": 0.0
        }, 
        "2": {
            "x": 0.86602540378443904, 
            "y": 11.5, 
            "z": 0.0
        }, 
        "3": {
            "x": 0.0, 
            "y": 11.0, 
            "z": 0.0
        }
    }
```

Here's the vertice in mesh2:
`'vertex': {'1': {'z': 0.0, 'y': 10.0, 'x': 0.0}, '0': {'z': 0.0, 'y': 11.707106781186546, 'x': -0.70710678118654768},  '3': {'z': 0.0, 'y': 11.0, 'x': 0.0}, '2': {'z': 0.0, 'y': 11.5, 'x': 0.86602540378443904}}, `

I find this problem while trying to run compas_ags.rootfinding in Rhino via compas.rpc. 
`independent_edges = list(form.edges_where({'is_ind': True}))` 
-> `independent_edges = [(k_i[u], k_i[v]) for (u, v) in list(form.edges_where({'is_ind': True}))]` solves the problem. 

I'm not sure whether this is a critical problem / could be solved. But maybe the same dictionary order would be more convient.

**Comment by tomvanmele** [comment]
ordering of data structure elements is irrelevant. if you run into problems with this, you are not doing it right :)

as you already suggested yourself, you just have to make sure to always use the `key_index` maps when converting to lists and back.

so, no, this is not a bug nor a problem :)

however, this seems to be an under-documented aspect of the implementation of the data structures, and a constant source of confusion.

i am working on an update of the tutorials in which this will be addressed specifically.
