### ISSUE TITLE
Diagnose performance issues with vertex attribute view

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#562]
During the resolution of #560, we noticed the vertex attribute view object has some severe performance issues when running on IronPython. The issue was resolved side-stepping the view, but the underlying problem of this class should be diagnosed and resolved.

**To Reproduce**

1. Open Rhino editor or run the following script using IronPython CLI (`ipy`):
```python
from timeit import default_timer as timer
import compas
from compas.datastructures import Mesh

t0 = timer()
mesh = Mesh.from_ply(compas.get_bunny())
print('mesh load time: {:.2f}s'.format(timer() - t0))

t1 = timer()
for _ in mesh.vertices(False):
    pass
print('vertex iterator without attribute view: {:.2f}s'.format(timer() - t1))

t2 = timer()
for _ in mesh.vertices(True):
    pass
print('vertex attribute view iterator: {:.2f}s'.format(timer() - t2))
```
which will output something like:
```
mesh load time: 2.26s
vertex iterator without attribute view: 0.03s
vertex attribute view iterator: 125.96s
```

For reference, the exact same script outputs the following when executed using cpython:
```
mesh load time: 2.09s
vertex iterator without attribute view: 0.01s
vertex attribute view iterator: 0.13s
```

**Minimal reproduction**
After some more debugging, it turns out that the problem is the `ABCMeta` metaclass, which somehow causes IronPython to go crazy if hundreds of instances are created in a row. The following minimal code snippets reproduces the issue in isolation, and the exact same code, but removing the `__metaclass__` declaration works perfectly fine:

```python
from abc import ABCMeta

class T(object):
    __metaclass__ = ABCMeta

    def __init__(self):
        super(T, self).__init__()

class J(T):
    def __init__(self):
        super(J, self).__init__()

for i in range(100000):
    a = J()
    if i % 200 == 0:
        print(i)
```

**Expected behavior**
The run time of iterating vertices with attributes should **not be 4000x slower** 😛 

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version: IronPython 2.7.8 / Rhino 6
 - Python package manager: `conda`
 - compas version: `0.16.1`

**Comment by gonzalocasas** [comment]
The problem seems to come from `MutableMapping`.
Apparently, the IronPython implementation sucks real bad.
@brgcode what do we use `MutableMapping` for?

**Comment by tomvanmele** [comment]
proper form i guess :)

**Comment by tomvanmele** [comment]
it also provides a bit of base functionality that we don't really use but that one might expect to get from a dict
