### ISSUE TITLE
Documentation missing for compas_rhino.geometry and .utilities

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#586]
# Feature Request

As a user who need to depend on documentation, I want `compas_rhino` fuctions to be documented. Ideally with simple examples.

## Details

1. For example **all** the classes on this page have unclickable links: https://compas-dev.github.io/main/api/compas_rhino.geometry.html

2. Another example, 90% of all methods in this page do not have a single character of documentation: https://compas-dev.github.io/main/api/compas_rhino.utilities.html

**Comment by tomvanmele** [comment]
this should be solved now...

**Comment by nortikin** [comment]
but it is not solved
404

**Comment by tomvanmele** [comment]
the urls have changed

https://compas-dev.github.io/compas/api/compas_rhino.utilities.html
https://compas-dev.github.io/compas/api/compas_rhino.geometry.html

**Comment by yck011522** [comment]
@nortikin 
Yes, I believe the permalink changed to the following:
https://compas-dev.github.io/compas/api/compas_rhino.geometry.html
https://compas-dev.github.io/compas/api/compas_rhino.utilities.html
