### ISSUE TITLE
compas_cgal not yet public

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#590]
# Feature Request

@brgcode Thanks for the presentation in the NCCR meeting today.
I'm interested in the [compas_cgal](https://github.com/BlockResearchGroup/compas_cgal) plugin. However, I believe it is not made public yet. 

I'm quite excited for the boolean operations. A quick question is, is this IronPython (GHPython in particularly) compatable or cpython only? If not can I call the boolean functions via proxy? Thanks

**Comment by gonzalocasas** [comment]
it's the latter: CGAL-based code only works in cpython, but it can be used from GH using the proxy.

**Comment by tomvanmele** [comment]
will make it public tomorrow. just have to update the docs...

**Comment by tomvanmele** [comment]
`compas_cgal` is now public...
