### ISSUE TITLE
##[error]remote: Permission to compas-dev/compas.git denied to github-actions[bot].

### ISSUE THREAD

**Issue by KEERTHANAUDAY** [compas-dev/compas#606]
Hi !

I tried to submit a PR for docs #604 . My build fails at Deploy docs step with the error message,

```
##[error]remote: Permission to compas-dev/compas.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/compas-dev/compas.git/': The requested URL returned error: 403
```

**To Reproduce**
1. Make docs change.
2. Make PR request

**Screenshots**
![Capture](https://user-images.githubusercontent.com/43433132/91036675-0e2a4700-e608-11ea-84e0-04ca68bae1ef.JPG)

**Desktop (please complete the following information):**
 - Windows 10
 - Python version 3.8.5
 - Python package manager - conda
- git version 2.27

**Additional context**
I tried upgrading my git version and passing a build twice and I received the same ever each time. I could not find any solution online.

**Comment by gonzalocasas** [comment]
is this fixed?

**Comment by tomvanmele** [comment]
no have had the same problem with other repos. seems that if you don't have write access the deploy thing doesn't work...

**Comment by gonzalocasas** [comment]
As mentioned in one of the open PRs, this would be solved if we switch the `GITHUB_TOKEN` for `GH_PAT` (personal access token).

**Comment by tomvanmele** [comment]
this should now be solved...
