### ISSUE TITLE
Importing Grasshopper

### ISSUE THREAD

**Issue by beverlylytle** [compas-dev/compas#610]
**Describe the bug**
In a Grasshopper script, compas may not realize that it is running in Grasshopper.

**To Reproduce**
1. Run `compas_rhino.install` in a new compas environment.
2. Open a new Grasshopper canvas.

3. In a new GhPythonScript (with a Panel wired to `out`), run the following:
```
import compas
print(compas.GH)
```

**Expected behavior**
"True" should appear in the Panel.

**Screenshots**
<img width="815" alt="Screenshot 2020-09-09 at 17 38 19" src="https://user-images.githubusercontent.com/57254617/92620734-477adc00-f2c3-11ea-81d6-35d3d9303cc6.png">

**Desktop (please complete the following information):**
 - OS: Mac 10.15.5
 - Python version: IronPython
 - Python package manager: conda

**Additional context**
This problem was encounter with compas version 0.16.2-9f955a9f.

**Comment by beverlylytle** [comment]
For anyone else who encounters this problem, a quick fix would be to add at the top of your script:
```
from compas_rhino import unload_modules
unload_modules('compas')

**Comment by beverlylytle** [comment]
This appears to be out of date now, however I believe the issue is still the same with `compas.RHINO`.

**Comment by beverlylytle** [comment]
No, it does not.  Closing the issue.

**Comment by tomvanmele** [comment]
i have removed `compas.GH` because we don't actually use it anywhere...
