### ISSUE TITLE
edges_on_boundaries for Mesh not closed

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#619]
line 1379 in mesh.py

_change:_
edgegroups.append(list(pairwise(vertices)))
_to:_
edgegroups.append(list(pairwise(vertices + [vertices[0]])))

**Comment by tomvanmele** [comment]
please send a PR...

**Comment by tomvanmele** [comment]
as far as i can tell this is solved. please check and close if appropriate...
