### ISSUE TITLE
regarding 'proper processing' of edgedata from older jsons

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#633]
Assuming that the intention of the 'else' portion of the data.setter in halfedge is to enable the loading of jsons generated using the deprecated scheme (before early September)...  shouldn't edge keys be converted from the older format to the newer format inside the datasetter so that the edge-based methods in the newer compas can actually make use of the saved edge attributes (imported from the json with the older data format)?

so... something like this:

            for uv, attr in iter(edgedata.items()):
                uv = sorted(literal_eval(uv))
                uv = '-'.join([str(uv[0]), str(uv[1])])
                self.edgedata[uv] = attr or {}
                
otherwise... the edge attributes are out of reach by the newer compas methods.

**Comment by tkmmark** [comment]
and certainly, this example above is not optimised since edge attributes will be input twice (ie. uv and vu)

**Comment by tomvanmele** [comment]
thanks for pointing this out. it was indeed an issue! should be solved in dc3b06f8

**Comment by tomvanmele** [comment]
@tkmmark can this be closed?

**Comment by tkmmark** [comment]
Didn’t pull from the latest Master yet (too scared of what new surprises it may hold :P), but this commit looks okay, so sure.
