### ISSUE TITLE
edge_attributes() key error

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#636]
The edge key conversion from (int, int) to str(int)+'-'+str(int) in **edge_attributes** causes problems, since it calls **edge_attribute**, which would already be taking care of the conversion later on.  So when one uses edge_attributes now, one receives an error as the key sent by **edge_attributes** to **edge_attribute** , now already a string, cannot be unpacked into u, v.

**Comment by tkmmark** [comment]
_Would suggest relocating the line...__

key = "-".join(map(str, sorted(edge)))

_to inside..._

'if not names'
(because this is the only portion of the definition that works directly with edgedata...)

_and modifying the first line to_

u, v = key = edge

**Comment by tomvanmele** [comment]
this should also be fixed since dc3b06f8

**Comment by tomvanmele** [comment]
@tkmmark can this be closed?
