### ISSUE TITLE
Support read/write from file-like objects and URL reads

### ISSUE THREAD

**Issue by beverlylytle** [compas-dev/compas#641]
# Feature Request

As a compas_fab dev, I want to be able to create meshes from STLs held at URLs so that compas_fab integration tests can use STLs stored in compas DATA.

## Details

**Describe the solution you'd like**
STLReader.filepath should be able to handle filepaths, urls and file-like objects.  This should be true for all compas file Readers.

**Comment by gonzalocasas** [comment]
Draft PR: https://github.com/compas-dev/compas/pull/712
