### ISSUE TITLE
dtype assumes a particular package structure

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#653]
Base.py and encoder.py currently assumes that the name of the module for importing a compas-based datastructure is the first two entries in **".__class__.__module__".split('.')**.  This assumes that all datastructures can be assessed at the second level of a compas-based package.

While that is fine for the compas core datastructures, such as Mesh, which indeed can be imported from "compas.datastructures", other compas users may have their datastructures contained at a different level.  For instance, my Form is located in "markymark.datastructures.diagrams".  

Therefore consider revising **".__class__.__module__".split('.')[:2]** to **".__class__.__module__".split('.')[:-1]**

**Comment by tomvanmele** [comment]
solved since 001b0b4b
