### ISSUE TITLE
feature_request: DataEncoder support for iterators and generators

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#654]
Useful in cases where proxy-wrapped methods output generators/iterators...

**Consider adding the following lines:**

if hasattr(o, '__ next __'):
	return list(o)
	
**to class DataEncoder's def default()...**

*hasattr is used instead of isinstance(o, type) because Python 2.x does not have modules such as typing.Generator/Iterator

**Comment by tomvanmele** [comment]
solved since 001b0b4b
