### ISSUE TITLE
many tutorials and pages on the compas.dev website give 404 errors. Didn't know where else to submit this issue.

### ISSUE THREAD

**Issue by tristanryerparke** [compas-dev/compas#658]
Webpages such as:
[https://compas.dev/compas/tutorial.html](url)
[https://compas.dev/compas/environments/](url)
are giving 404 errors.
Without the tutorials page, it is hard for me to get started.
Cheers

**Comment by tomvanmele** [comment]
thanks for pointing that out. should be fixed now...

**Comment by tristanryerparke** [comment]
Also, The

**Comment by gonzalocasas** [comment]
@brgcode how about we add this here to prevent this from happening?https://github.com/gramaziokohler/workshop_munich_2020/blob/master/.github/workflows/check-markdown-links.yml

**Comment by tomvanmele** [comment]
@Licini could you have a look at this?
