### ISSUE TITLE
trimesh slice_mesh_plane function

### ISSUE THREAD

**Issue by mattiskoh** [compas-dev/compas#659]
# Feature Request

I would like to be able to 'split' meshes using planes (or other meshes), and have it return the newly split mesh (and not a polyline)

The trimesh library has a function that does exactly what I would like i.e. `slice_mesh_plane` : "slice a mesh with a plane, returning a new mesh that is the portion of the original mesh to the positive normal side of the plane"

## Details

**Is your feature request related to a problem? Please describe.**
see example below

**Describe the solution you'd like**
Implementing the slice_mesh_plane function from the trimesh library

**Describe alternatives you've considered**
Using the cgal libary.

**Additional context**
![image](https://user-images.githubusercontent.com/17108767/98576685-30ed0300-22bb-11eb-9661-f74f7fbe276a.png)
example, cut this open face with a box, or one of the faces of the box (which would be a plane)

**Comment by tomvanmele** [comment]
there is a pure Python version of this available. not sure about performance though. perhaps you could try it out and let me know...

```python
from compas.geometry import Plane
from compas.geometry import Box
from compas.datastructures import Mesh

plane = Plane((0, 0, 0), (1, 0, 0))
box = Box.from_width_height_depth(1, 1, 1)
mesh = Mesh.from_shape(box)
result = mesh.slice_plane(plane)

print(len(result) == 2)
```
