### ISSUE TITLE
api reference showing draw_collection functions that have been removed

### ISSUE THREAD

**Issue by mattiskoh** [compas-dev/compas#660]
**Describe the bug**
draw_collection() has been removed for the PolylineArtist as well as LineArtist, however are still shown in the API refernce.
![image](https://user-images.githubusercontent.com/17108767/98645985-02127380-2333-11eb-85e5-a359adbcf284.png)

**To Reproduce**
1. Context [e.g. ST3, Rhino, Blender, ...]
2. Sample script
3. Sample data

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python version [e.g. 2.7]
 - Python package manager [e.g. macports, pip, conda]

**Additional context**

**Comment by tomvanmele** [comment]
i think this is no longer the case. could check and close if solved? thanks...

**Comment by gonzalocasas** [comment]
nope, they are still showing up.

**Comment by tomvanmele** [comment]
i guess this is because the default configuration of invoke docs changed...

**Comment by gonzalocasas** [comment]
@brgcode you mean, to not rebuild? but this is done on CI, so, I don't think there's any cached data/leftover from previous builds.

**Comment by tomvanmele** [comment]
@Licini could you have a look at this...

**Comment by beverlylytle** [comment]
`draw_collection` has been removed for `PolylineArtist` and `LineArtist` in compas_rhino, but not in compas_ghpython.  So the API reference is accurate.  I guess the question is, which `draw_collection` methods should stay and which should go?

**Comment by tomvanmele** [comment]
i think they should all go :)

**Comment by beverlylytle** [comment]
Even the recently added `BoxArtist.draw_collection`?

**Comment by tomvanmele** [comment]
yup. unless you object :)

**Comment by beverlylytle** [comment]
Not at all.
