### ISSUE TITLE
unify meshplotter within geometryplotter (artist) framework

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#661]
Designers often need to simultaneously visualise stand-alone geometries with COMPAS datastructures like Meshes or Networks (e.g. seeing the results of trimesh_pull_points).   Would be great to bring the older plotter setup under the newer geometry artist framework, so that the workflow for developers can be simplified into something closer to...

plotter = GeometryPlotter()
plotter.add(mesh)
plotter.add(lines)
plotter.show()

**Comment by tkmmark** [comment]
As a quick fix, even some mesh_plot_instance.to_geometry_artists() would be helpful.

**Comment by tomvanmele** [comment]
it is indeed the goal to allow all types of COMPAS objects to be added to plots in the style supported by the geometry plotter. in the meantime, can you not use the methods `draw_points`, `draw_lines`, `draw_...` of the `MeshPlotter`?

**Comment by tkmmark** [comment]
yes, I can, which brings me to a suggestion I have forgotten to include in my last comment: "'it would also be helpful, as a quick interim fix, to introduce some methods like `geom_artist.to_plotter_dict()`"

**Comment by tkmmark** [comment]
The preference for geometry plotter is due to its ability to handle styles in a model-scale-invariant way... (see figure)
![image](https://user-images.githubusercontent.com/9421670/98708761-d23e8c80-2381-11eb-9a73-5109e06e797a.png)
top row: mesh plotter
bottom row: geom plotter
left col: scale factor 1
right col: scale factor 3

**Comment by jf---** [comment]
@tomvanmele || @gonzalocasas bump

**Comment by gonzalocasas** [comment]
I think this should be closed, the plotters don't exist anymore

**Comment by gonzalocasas** [comment]
re-open if i'm wrong though :)
