### ISSUE TITLE
draw_points argument in PolylineArtist not functional

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#662]
**Consider making the following insertions (as highlighted):**

![image](https://user-images.githubusercontent.com/9421670/98709492-b8517980-2382-11eb-8c93-5640285040dd.png)

**For the developers' copy-and-paste-convenience, the code has been reproduced here as text:**

self._points_artists = []

if self._draw_points:
	for point in self.polyline:
		self._points_artists.append(self.plotter.add(point))

**Setup is based on LineArtist... and tested, as shown below:**

![image](https://user-images.githubusercontent.com/9421670/98709656-f77fca80-2382-11eb-8a7b-1bb40d8a4986.png)

**Comment by jf---** [comment]
@tomvanmele || @gonzalocasas, any thoughts on this contribution?

**Comment by gonzalocasas** [comment]
make sense, I haven't checked if this is still the case with the new 2.0 release and the scene stuff. @tkmmark would you mind creating a PR for this?

**Comment by tomvanmele** [comment]
this is related to the plotter, which doesn't exist anymore...
