### ISSUE TITLE
arguments incorrect for single object selections via compas_rhino 

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#672]
In compas_rhino.utilities.objects.py...

_Consider revising all corresponding lines in **select_line()**, **select_curve()** from..._

rs.GetObject(message, preselect=True, select=True, group=False, filter=rs.filter.curve)

_to_

rs.GetObject(message, preselect=True, select=True, filter=rs.filter.curve)

**Comment by tomvanmele** [comment]
should be solved since 32a71d7a
please check and close if appropriate...
