### ISSUE TITLE
Suggest downgrading the Raise in DataDecoder's dtype to a printed warning...

### ISSUE THREAD

**Issue by tkmmark** [compas-dev/compas#678]
Because 'dtype' is such a common attribute name... a **raise** is somewhat excessive, especially in cases where a COMPAS-based developer may be using the DataDecoder to decode serialisable data from non-COMPAS sources...  Consider downgrading the raise for the **ValueError Exception** block at minimum, and introducing a **Else** block to let **cls.from_data(o['value'])** work its magic when a supplied **dtype** does match the correct specification.

![image](https://user-images.githubusercontent.com/9421670/100172254-32781700-2ec8-11eb-98bd-9c35bedef3e7.png)

**Comment by tomvanmele** [comment]
this is not an issue nor a feature request, but a PR in the making. please suggest code updates through PRs...

**Comment by tkmmark** [comment]
ok
