### ISSUE TITLE
Add `Update` section to documentation

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#697]
Current documentation has detailed instructions to install with `conda`, `pip` and source installs, but no information about how to update, and while the update is trivial, it would make life of users easier if it's spelled out in a short section below [`Installation`](https://compas.dev/compas/latest/installation.html).

Also applies to `compas_fab` package.

**Comment by tetov** [comment]
Closed in 0859f2f933ba31e7f49f9c00e35ac62235638c8d and compas-dev/compas_fab#256?
