### ISSUE TITLE
Documentation links not working

### ISSUE THREAD

**Issue by Mistrymm7** [compas-dev/compas#698]
https://github.com/compas-dev/compas_cgal

The reference links for CGAL documentation and examples are not working.
https://compas.dev/compas_cgal/
 https://compas.dev/compas_cgal/examples.html

**Comment by tetov** [comment]
This could be closed in favour of compas-dev/compas_cgal#7 and compas-dev/compas_cgal#8. @brgcode

**Comment by tomvanmele** [comment]
there was a bad redirect url in the top level index file on the gh-pages branch. should be fixed now...
