### ISSUE TITLE
There is no Vector.normalize() 

### ISSUE THREAD

**Issue by isabelmdo** [compas-dev/compas#699]
**Describe the bug**
There is no Vector.normalize() method as described in the tutorial.

**To Reproduce**
1. Context: Following tutorial steps
2. [Geometry tutorial:](https://compas.dev/compas/latest/tutorial/geometry.html)
Sample script:
```
>>> x = Vector(1, 0, 0)
>>> type(x)
<class 'compas.geometry.primitives.vector.Vector'>
>>> x.normalize()       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Vector' object has no attribute 'normalize'
```

**Expected behavior**
I expected to see no output, like in the Geometry Tutorial.

**Screenshots**
Here is a screenshot of the tutorial:
![image](https://user-images.githubusercontent.com/40008482/101896625-062aee80-3b88-11eb-8af4-1b32d631c30d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.6
 - Python package manager: conda

**Additional context**
This, in the other hand, works just fine:
```
>>> compas.geometry.normalize_vector(x)      
[1.0, 0.0, 0.0]
```

**Comment by tetov** [comment]
`Vector.unitize` exists. Doc change?
