### ISSUE TITLE
BaseMesh attributes documentation is wrong

### ISSUE THREAD

**Issue by Achillx** [compas-dev/compas#704]
**Describe the bug**
The [online documentation](https://compas.dev/compas/latest/api/generated/compas.datastructures.BaseMesh.html#compas.datastructures.BaseMesh), shows `max_int_key` attributes that do not exist in `Mesh.data` dictionary. Also accessing the `data` attribute returns a dict that contains `compas` `datatype` and `data` (again!)

**To Reproduce**
Run the following code:
```
from compas.geometry import Box
from compas.datastructures import Mesh

box = Box.from_width_height_depth(2, 2, 2)
box = Mesh.from_shape(box)
print(box.name)
print(box.data.keys())
print(box.data['data'].keys())
print(box.data['data']['max_face'])
# The line bellow will fail
print(box.data['max_face'])
```

**Expected behavior**
Get for example `max_face` but calling `Mesh.data['max_face']`

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Python version: 3.7.6
 - Python package manager : conda
 - Compas: 0.91.1

**Comment by tomvanmele** [comment]
left-over from old code. will remove it...

**Comment by tomvanmele** [comment]
solved since 3cf2bd98

**Comment by Achillx** [comment]
I would also add this to the css styles:
```
.graphviz img {
    width: 100%;
}
```

It would fix the overflow issue seen below.
![Screenshot 2020-12-14 at 13 04 42](https://user-images.githubusercontent.com/38357732/102079438-038cfb00-3e0d-11eb-84e4-91f3185a4a21.png)

**Comment by tomvanmele** [comment]
already did, refresh page...

**Comment by Achillx** [comment]
One more comment.
Personally and maybe for others, is very useful to get the last face or vertex index. Sure we can get it through `Mesh.data['data']['max_vertex']`, but now that the whole `data` dictionary is not documented it is very much hidden and a bit counter-intuitive that you need to access data twice. I'm not saying it is a bug, but it would be nice to have another attribute for `data` and be able to call `Mesh.data['max_vertex']`.

**Comment by tomvanmele** [comment]
the data dict is not meant to be used this way. perhaps we should underscore the attribute name. `max_vertex` is an attribute of the mesh and can be consulted at all times. will assign a property to this...
