### ISSUE TITLE
Documentation: midpoint_point_point

### ISSUE THREAD

**Issue by nizartaha** [compas-dev/compas#714]
This function can compute the midpoint of two points, even if both are not laying in the XY-plane

to change:
`Compute the midpoint of two points lying in the XY-plane.`

Reference:
https://compas.dev/compas/latest/api/generated/compas.geometry.midpoint_point_point.html?highlight=mid#compas.geometry.midpoint_point_point

**Comment by tetov** [comment]
Fixed in 27f16a3?

**Comment by tomvanmele** [comment]
yes indeed
