### ISSUE TITLE
Cannot import `compas_rhino` from Grasshopper (GHPython)

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#73]
Currently it is not possible to import any `compas_rhino` functionality from Grasshopper, mainly because of three lines:
 - [this one on `layers.py`](https://github.com/compas-dev/compas/blob/master/src/compas_rhino/utilities/layers.py#L10). 
 - [this one on `objects.py`](https://github.com/compas-dev/compas/blob/master/src/compas_rhino/utilities/objects.py#L8). 
 - [and this one on `drawing.py`](https://github.com/compas-dev/compas/blob/master/src/compas_rhino/utilities/drawing.py#L37)

Regarding the decision of an additional `compas_grasshopper` package, the impossibility to import the namespace is very confusing, especially because the error message is also very misleading.

To reproduce, simply drop a GHPython component on an empty GH canvas, and type `import compas_rhino`:

![image](https://user-images.githubusercontent.com/933277/37658406-bbd1b270-2c4d-11e8-8f61-c83173504fc0.png)

**Comment by Rippmann** [comment]
I ran into the same problem today.

**Comment by gonzalocasas** [comment]
Pull request available: https://github.com/compas-dev/compas/pull/74

**Comment by tomvanmele** [comment]
solved in pull request #74
