### ISSUE TITLE
Maximum height limitation

### ISSUE THREAD

**Issue by archz2** [compas-dev/compas#787]
I am trying to build a shell structure with height of 80 mm but the result gives me 27.1mm. 

How can I ensure about the maximum height limitation with respect to the shape in the plan?

![image](https://user-images.githubusercontent.com/66735186/111279620-e01e5a00-8660-11eb-850e-ed491b4c3ce4.png)

[80 height, but result 27.1.zip](https://github.com/compas-dev/compas/files/6147262/80.height.but.result.27.1.zip)

The zip file has the rv2 file and the 3dm file.

**Comment by gonzalocasas** [comment]
@brgcode this issue probably should move to https://github.com/BlockResearchGroup/compas-RV2, right?

**Comment by tomvanmele** [comment]
yes indeed...

**Comment by gonzalocasas** [comment]
i thought `Transfer issue` would work, but it seems it only works across repos of the same org. 🤔

**Comment by archz2** [comment]
Oh. Really sorry. Please delete this thread.


 I have re-posted my query here. 

https://github.com/BlockResearchGroup/compas-RV2/issues/256

**Comment by gonzalocasas** [comment]
😉
