### ISSUE TITLE
cannot import mesh_transform 

### ISSUE THREAD

**Issue by beverlylytle** [compas-dev/compas#789]
**Describe the bug**
Compas_fab tests are failing with
```
from compas.datastructures import mesh_transform
E    ImportError: cannot import name 'mesh_transform'
```

**To Reproduce**
1. Context [e.g. ST3, Rhino, Blender, ...]
2. Sample script
3. Sample data

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python version [e.g. 2.7]
 - Python package manager [e.g. macports, pip, conda]

**Additional context**

**Comment by tomvanmele** [comment]
hmm yes i limited the import of functions to those not already attached to the mesh itself... can put those back for now if you like?

**Comment by gonzalocasas** [comment]
yep, we should put them back in, otherwise it's a breaking change that would need 2.x to be released. I'll do it and send a pr in a bit

**Comment by gonzalocasas** [comment]
Fixed with https://github.com/compas-dev/compas/pull/790
