### ISSUE TITLE
Unetary support for vectors

### ISSUE THREAD

**Issue by jf---** [compas-dev/compas#795]
there seems no method of reversing / inverting a `compas.geometry.Vector` 
its pretty readible to write `Frame(pnt, -vX, -vY)`
this is mostly syntactically I suppose

```python
def invert(): # Transformation has this method
   self.scale(-1.)

def __neg__(self):
   return self.scaled(-1.)
```

**Comment by tomvanmele** [comment]
good idea. will do...

**Comment by jf---** [comment]
hi @brgcode here's a `PR` ( took 3x to get it right "the 1st time" 💩 )
