### ISSUE TITLE
network_find_cycles does not find faces in Mesh.from_lines()

### ISSUE THREAD

**Issue by lottilotte** [compas-dev/compas#808]
Hi,  I'm trying to create a mesh from a network. However, it doesn't work how I would like it to:

This is my network:
<img width="850" alt="Screenshot 2021-04-08 at 09 50 35" src="https://user-images.githubusercontent.com/56078765/113989069-5d984d00-9850-11eb-88ea-e0455aa9c40a.png">
This is how I would like it to be meshed:
<img width="850" alt="Screenshot 2021-04-08 at 09 50 26" src="https://user-images.githubusercontent.com/56078765/113989156-73a60d80-9850-11eb-8411-b0c63b75c96e.png">
But this is what I get:
<img width="850" alt="Screenshot 2021-04-08 at 09 50 42" src="https://user-images.githubusercontent.com/56078765/113989187-7d2f7580-9850-11eb-85cc-3c222ded2f93.png">

It seems like the network_find_cycles(network) is not functional?

```
import os

from compas.datastructures import Network
from compas.datastructures.mesh._mesh import Mesh

# ==============================================================================
# Paths
# ==============================================================================

HERE = os.path.dirname(__file__)
DATA = os.path.abspath(os.path.join(HERE, '..', 'data'))
FILE_I = os.path.join(DATA, 'ccf_3d.json')

# ==============================================================================
# Network to Mesh
# ==============================================================================

network = Network.from_json(FILE_I)
# lines = network.to_lines()
# mesh = Mesh.from_lines(lines, delete_boundary_face=True)


# ==============================================================================
# test the definition
# ==============================================================================

from compas.datastructures import network_find_cycles

vertices = network.to_points()
faces = network_find_cycles(network)
**# the faces are not found properly**: 
**# the output is: [[13, 7, 12, 19, 20, 3, 29, 9, 32, 11, 17, 30, 15, 8, 0, 21, 14, 1, 23, 25, 31, 16, 13], [0, 8, 17, 6, 27, 30, 17, 8, 15, 30, 27, 6, 24, 5, 4, 22, 18, 10, 26, 28, 2, 7, 13, 16, 12, 7, 2, 28, 12, 16, 31, 19, 26, 10, 20, 25, 23, 3, 18, 22, 29, 3, 23, 1, 29, 22, 4, 9, 29, 1, 14, 9, 4, 5, 32, 9, 14, 21, 32, 5, 24, 11, 32, 21, 0], [0, 11, 24, 6, 17, 11, 0], [18, 3, 20, 10, 18], [12, 28, 26, 19, 12], [20, 19, 31, 25, 20]]
# but it should be a regular quad mesh**

mesh = Mesh.from_vertices_and_faces(vertices, faces)

mesh.delete_face(0)
mesh.cull_vertices()


# ==============================================================================
# Visualisation
# ==============================================================================

from compas_rhino.artists import NetworkArtist
from compas_rhino.artists import MeshArtist

artist = NetworkArtist(network, layer="Network")
artist.clear_layer()
artist.draw()


artist = MeshArtist(mesh, layer="Mesh")
artist.clear_layer()
artist.draw()
```

[ccf_3d.json.zip](https://github.com/compas-dev/compas/files/6277019/ccf_3d.json.zip)

Many thanks!

**Comment by tomvanmele** [comment]
making a mesh like this only works if the network is planar in projection. just transform the lines using a bestfit frame and transform back once the mesh is created...

**Comment by lottilotte** [comment]
ok many thanks, this works nicely for one fold:

<img width="850" alt="Screenshot 2021-04-08 at 10 54 24" src="https://user-images.githubusercontent.com/56078765/113998070-0054c980-9859-11eb-8e24-0195807bf439.png">

however, for multiple folds I will have to split it for the meshing I guess...
<img width="850" alt="Screenshot 2021-04-08 at 10 55 19" src="https://user-images.githubusercontent.com/56078765/113998169-182c4d80-9859-11eb-9078-497ff29ca68e.png">

**Comment by tomvanmele** [comment]
how do you get to the folded line geometry to begin with?
if you can base the meshing on an unfolded version the solution is similar as above.
not that you only need to know the topology for the mesh generation.
the geometry can be snapped to any configuration afterwards...

**Comment by tomvanmele** [comment]
also you can modify the face finding algorithm to only take the local neighbourhood of a node into account instead of the global geometry...

**Comment by lottilotte** [comment]
> to only take the local neighbourhood of a node into account instead of the global geometry...

wouldn't this be ideal in general or is there a reason why one would want the global geometry?

**Comment by tomvanmele** [comment]
more complicated and a bit slower, but yes...

**Comment by lottilotte** [comment]
indeed seems complicated to me :see_no_evil:
