### ISSUE TITLE
compas.topology.astar_shortest_path fails with AttributeError

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#810]
**Describe the bug**
`astar_shortest_path` fails on networks because it expects `network.vertex_coordinates` which is now `network.node_coordinates`.

**To Reproduce**
```
from compas.datastructures import Network
from compas.topology import astar_shortest_path 
n = Network()
a = n.add_node(x=1, y=2, z=0)
b = n.add_node(x=3, y=1, z=0)  
n.add_edge(a, b) 
astar_shortest_path(n, a, b)
```

Fails with 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gcasas\anaconda3\envs\compas-fs2021\lib\site-packages\compas\topology\traversal.py", line 358, in astar_shortest_path
    root_coords = network.vertex_coordinates(root)
AttributeError: 'Network' object has no attribute 'vertex_coordinates'
```

**Desktop (please complete the following information):**
 - `compas 1.1.0`

**Comment by tomvanmele** [comment]
should be an easy fix, but also noticed that the current implementation is specifically about geometrical distance, and specifically for networks. we could move it out of topology and into datastructures, but that would still make it specific to networks. other option is to do something similar as with the dijkstra version: add a function that computes distances based on user-defined edge weights. those edge weights could be computed by the user as the distances between connected nodes (network) or vertices (mesh).
