### ISSUE TITLE
area_triangle returns false result, geometry/_core/normals.py returns partial vector

### ISSUE THREAD

**Issue by gidodielemans** [compas-dev/compas#812]
Using the function area_triangle in compas version 1.4.0 returns a value 0.5 times the expected result.
Cause seems to be a result of the normal_triangle function returning a vector with half the length.

```
a = [0.0, 0.0, 0.0]
b = [1.0, 0.0, 0.0]
c = [0.0, 1.0, 0.0]

# construct two vectors from start and end points
ab = Vector.from_start_end(a, b)
ac = Vector.from_start_end(a, c)

# the length of the cross product
L = ab.cross(ac).length

# compute the area of a triangle defined by three points
A = area_triangle([a, b, c])
# Area of the triangle as calculated by compas
print(A)
# half the length of the cross product equals the area of the triangle
print(0.5 * L)
```

Expected is a value of 0.5 for the area of the triangle, though a value of 0.25 is returned.
Only applies to compas version 1.4, in other versions it returns as expected.
Commit that changes the function seems to be the following:
https://github.com/compas-dev/compas/commit/db51f513943081e5ad5455ea920bae71adf4b10c#diff-40b922ec2c8849915b6426bbfad30a5d1a5b4749fd62349057cce5575822c355

 - OS: Windows 10 Pro
 - Python version 3.8
 - Python package manager Anaconda 3

**Comment by tomvanmele** [comment]
thanks for pointing that out. should be solved with PR #814
