### ISSUE TITLE
plane.py -> get/set error

### ISSUE THREAD

**Issue by funkchaser** [compas-dev/compas#82]
Hi,
In geometry.objects.plane Plane - I'm getting errors here.
Shouldn't it be `key` instead of `i` in the conditional statements?

    `def __getitem__(self, key):
        if i == 0:
            return self.point
        if i == 1:
            return self.normal
        raise KeyError

    def __setitem__(self, key, value):
        if i == 0:
            self.point = value
            return
        if i == 1:
            self.normal = value
            return
        raise KeyError`

**Comment by tomvanmele** [comment]
solved in hotfix 0.1.0-#82
