### ISSUE TITLE
mesh_explode command

### ISSUE THREAD

**Issue by nizartaha** [compas-dev/compas#831]
**Describe the bug**
mesh_explode in compas seems that it doesnt behave as rhino explode command when exploding a closed mesh (boxy sort of typology). mesh is exported as stl from rhino (i tried also to export it as obj).

I am not sure if that is a bug or a feature request.

**To Reproduce**
```
import os
from compas.datastructures import Mesh, mesh_explode

HERE = os.path.dirname(__file__)
file_mesh = os.path.join(HERE, 'boxyMesh.stl')

mesh = Mesh.from_stl(file_mesh) 
mesh_parts = mesh_explode(mesh)
print(len(mesh_parts))
```

**Expected behavior**
in Rhino it returns 8 meshes and in compas it returns a list of only 1 element.

**Screenshots**
![image](https://user-images.githubusercontent.com/38039580/117336451-825a0180-ae9c-11eb-8e4e-61ae8d6aaefe.png)

**Comment by gonzalocasas** [comment]
@nizartaha could you please attach the STL you used as example?

**Comment by tomvanmele** [comment]
can you send me the STL?

**Comment by tomvanmele** [comment]
haha

**Comment by nizartaha** [comment]
haha, thank you for the quick response. i tried to drop it actually but it didnt work.
here is it: https://we.tl/t-3ytvrFHSPk

**Comment by tomvanmele** [comment]
Rhino explodes a mesh along components separated by naked edges (i.e. into disconnected components).

the problem is that the STL reader automatically merges identical vertices. this means that the mesh no longer has disconnected components en therefore cannot be exploded...

**Comment by nizartaha** [comment]
i understand. Thanks. 
although if i import the same stl again to rhino and explode it returns 8 meshes. but maybe Rhino has a different STL reader?!

anyways, i tried to export it to ply, read it and it worked . I have 8 meshes as list. :) ill stick with PLY then. Thanks
```
file_mesh = os.path.join(HERE, 'boxyMesh.ply')
mesh = Mesh.from_ply(file_mesh)
```
