### ISSUE TITLE
Non-admin install

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#833]
Following up on https://github.com/compas-dev/compas_fab/issues/297, it would be good if we can make sure that a non-admin user can still install COMPAS. There are two parts (at least), one is supporting Rhino to be installed in non-standard locations, and the other one is the need for admin rights to create symlinks.

**Comment by tetov** [comment]
I looked into enabling Developer Mode to allow symlink creation without privilege escalation. However, turning on Developer Mode is most likely disabled on a computer managed by an organisation or company. 

Computers at Lund University and at the Swedish Board of Agriculture (a slightly odd test sample I guess) both have this setting managed by IT dept. 

![4A1F923C-F125-47C7-9769-0A0BE85B8A39](https://user-images.githubusercontent.com/14882117/119007657-bac80800-b991-11eb-952b-eee2f950bc96.png)

Catch-22 :/

**Comment by jf---** [comment]
@gonzalocasas conda addresses this?

**Comment by tetov** [comment]
This is not a problem for Py3 installs on Rhino 8. :)

**Comment by tomvanmele** [comment]
has nothing to do with `conda`, but simply with how packages were/had to be installed in Rhino 7 and below. will close this since this already partially resolved and will only get better from now on...
