### ISSUE TITLE
Expose draw_breps() at compas_rhino.utilities level and in documentation

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#854]
I discovered this function that seems to work perfectly fine, although it is not used anywhere else in the core library. 
But I realize it is not in the `__all__` list. 

I want to ask if this function is intended to continue to exist in the future? And if so, can this be included in the `__all__` list

https://github.com/compas-dev/compas/blob/d2ba3a237a548b6bd396cc00913cae03a7189044/src/compas_rhino/utilities/drawing.py#L423-L511

**Comment by yck011522** [comment]
I can _try_ create a PR for review.

**Comment by tomvanmele** [comment]
equally (or even more) important than including it in those lists is to add it to the import statement in `compas_rhino.utilities.__init__.py` at line 176...
