### ISSUE TITLE
Adding function to join the breps when calling draw_breps() 

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#855]
# Feature Request

As a [user who build my own RhinoArtist for my custom geometry classes], I want [to create polysurfaces/joinnedBreps using the draw_breps() function] so that [benefit].

## Details

**Is your feature request related to a problem? Please describe.**
Calling `compas_rhino.utilities.drawing.draw_breps()` with a list of input results in drawing multiple Breps. I want an option to create the the individual faces, join them, add them to doc and return the joined brep(s) guids.

**Describe the solution you'd like**
I think this can be backward compatible by using a flag.

**Comment by tomvanmele** [comment]
can you add an example script of a use case scenario?

**Comment by yck011522** [comment]
Yes, I can add an example to the docs to show that use case.

**Comment by tomvanmele** [comment]
no i mean can you add an example here to clarify the context of the requested functionality?

**Comment by yck011522** [comment]
Well, I added an example in the function's docs to show how to use: (check out the PR)

    Using a compas Mesh as an example:
    >>> from compas.datastructures import Mesh
    >>> from compas.geometry import Box, Frame
    >>> from compas_rhino.utilities import draw_breps
    >>> box = Box(Frame.worldXY(), 1.0, 2.0, 3.0)
    >>> mesh = Mesh.from_shape(box)
    Draw convert each mesh face to brep dict schema:
    >>> vertices = [mesh.vertex_attributes(vertex, 'xyz') for vertex in mesh.vertices()]
    >>> breps = []
    >>> for face in mesh.faces():
    >>>     face = {'points' : [vertices[vertex] for vertex in mesh.face_vertices(face)]}
    >>>     face['points'].append(face['points'][0])
    >>>     breps.append(face)
    Draw brep faces as one joined brep.
    >>> guids = draw_breps(breps, join=True)

Context is a bit harder to say. Many times we need to model polysurfaces. One example is my timber beams with joint features. The features are 3d polygonal shapes. Not necessary extrusions, but can easily be modeled with polysurfaces composed of planar surfaces.

**Comment by yck011522** [comment]
Arh, another example is for instance, if the existing compas_rhino.artist.PolyhedronArtist wants to change it's implementation from drawing the polyhedron as RhinoMesh objects to drawing it as Rhino Polysurface objects. 

Then you can simply use `draw_breps(breps, join=True)` as shown above to achieve it.

https://github.com/compas-dev/compas/blob/75072d9fcc1e2d0565c69d892ed16ead29b0f04a/src/compas_rhino/artists/polyhedronartist.py#L45-L82
