### ISSUE TITLE
Axis scale will be wrong if `axis` input for `RobotModel.add_joint()` is not unitized

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#864]
Refering to this function. 

https://github.com/compas-dev/compas/blob/6351a1d6116c519734d1ac7b5e62e543dc3c48e0/src/compas/robots/model/robot.py#L965

I was trying to create my own linear axis and mistakenly supplied a non-unitized vector. The result is that the axis scale will be off by the multiple of that axis's length. I believe this is not an intended feature and if so, the function should probably unitize user input internally as a precaution.

**Comment by beverlylytle** [comment]
Yeah, I agree with this.  Especially since it is a requirement within URDF http://wiki.ros.org/urdf/XML/joint
