### ISSUE TITLE
gh python compatible try-except don't work outside of IronPython

### ISSUE THREAD

**Issue by tomvanmele** [compas-dev/compas#88]

**Comment by gonzalocasas** [comment]
I assume you mean the changes here: https://github.com/compas-dev/compas/pull/74 but could you elaborate on what's the case that doesn't work? (Or why would you import `compas_rhino` when not inside IronPython)

**Comment by tomvanmele** [comment]
ha sorry i just filed the issue so i could fix and close, but then got distracted... :)

i often have to be able to indirectly run python files in CPython that are actually meant to be used only in Rhino. for example, to generate the UI files from a controller class.

the try-except doesn't work because it can't find `scriptcontext`

**Comment by tomvanmele** [comment]
solved on the develop branch only

**Comment by tomvanmele** [comment]
solved on the develop branch only
