### ISSUE TITLE
`compas_rhino.artists.RobotModelArtist.clear()` does not clear

### ISSUE THREAD

**Issue by yck011522** [compas-dev/compas#886]
**Describe the bug**
Can someone confirm if this is repeatable:

The `clear()` function in `compas_rhino.artists.RobotModelArtist` doesn't clear any geometry in the Rhino viewport.

https://compas.dev/compas/latest/api/generated/compas_rhino.artists.RobotModelArtist.clear.html#compas_rhino.artists.RobotModelArtist.clear

**To Reproduce**
1. Context [Rhino 6]
2. Load RobotModel from URDF
3. Something like this:
```
from compas.robots import RobotModel
from compas_rhino.artists import RobotModelArtist
# Drawin g is successful
robot_model = RobotModel.from_urdf_file(urdf)
robot_artist = RobotModelArtist(robot_model)
robot_artist.draw_collision()

# Try to clear the geometry is not successful

robot_artist.clear()
```

**Comment by tomvanmele** [comment]
is this now resolved?

**Comment by gonzalocasas** [comment]
WOMM
