### ISSUE TITLE
GhPython has no write access to tmpdir when using XFunc

### ISSUE THREAD

**Issue by andrewliew** [compas-dev/compas#90]
The Grasshopper Python component appears to use a non-user writable temp directory when running a Python script. Therefore the default ``tmpdir`` used by XFunc cannot handle the **.json** writing. 

Providing your own ``tmpdir`` with write access causes no issue, but many will not know that the error implies to do this.

**Comment by tomvanmele** [comment]
is it then sufficient to extend the error message with some instructions?

**Comment by andrewliew** [comment]
I think this would make sense. I do not think it is worth the effort making or finding a temporary folder that has write access, when a simple message saying they should provide one solves the problem.

**Comment by tomvanmele** [comment]
done, but only on develop...
