### ISSUE TITLE
VolMesh constructor from json data

### ISSUE THREAD

**Issue by Sam-Bouten** [compas-dev/compas#905]
In the construction of a volmesh from .json through halfface.py,
a TypeError is raised in add_halfface(self) on accessing the length property of an int.

running sample script _volmesh_IO.py_, with sample data _in_volmesh.json_:
[VolMesh_constructor.zip](https://github.com/compas-dev/compas/files/7205586/VolMesh_constructor.zip)
_in halfface.py, line 377, add_halfface if len(vertices) < 3:
TypeError: object of type 'int' has no len()_

Likely cause is in halfface.py, @data.setter (line 198):
_faces_ is appended to as a flattened list of ints (vertex indices),
while the add_cell(self, ...) method expects a nested list of list of ints:
```python
for c in cell:
    attr = cell_data.get(c) or {}
    faces = []
    for u in cell[c]:
    for v in cell[c][u]:
        faces.append(cell[c][u][v])
        self.add_cell(faces, ckey=int(c), attr_dict=attr)
```

My current workaround:
using implementation of Halfface.py from compas 0.17.2

Possible bug fix, **_not_** yet checked for side effects:
```python
for c in cell:
    attr = cell_data.get(c) or {}
    faces = []
    for u in cell[c]:
        faces.append([])
        for v in cell[c][u]:
            faces[-1].append(cell[c][u][v])
    self.add_cell(faces, ckey=int(c), attr_dict=attr)
```

environment:
windows 10, conda, python 3.8.12, compas 1.8.1

**Comment by jf---** [comment]
@tomvanmele || @gonzalocasas seems the PR is closed the corresponding issues wasn't?
