### ISSUE TITLE
Versions in documentation

### ISSUE THREAD

**Issue by gonzalocasas** [compas-dev/compas#933]
The current docs have two issues regarding the versions dropdown:
 1. the sorting is alphabetical, so the newer versions like `1.11.1` are listed after `1.2.0` instead of above `1.9.3`
 2. the docs are defaulting to `1.7.1` instead of latest

**Comment by Licini** [comment]
Hey @gonzalocasas 
1. I just added proper sorting in sphinx template (https://github.com/compas-dev/sphinx_compas_theme/commit/292090f07b5559d9c77843e2c44c06e96d72a116)
Should be working now if you clear the cache and load the doc site

2. @tomvanmele I think we decided `/latest` is not gonna be used anymore, instead `compas.dev/compas` will be directly forwarded to latest release and `dev` on top of drop list points to the latest commits from main branch. The current `latest` folder is actually leftover of old time which we should delete now. https://github.com/compas-dev/compas/pull/937

3. I just released somehow it's not removing older patches anymore, and gh-pages branch might runout of space soon again.... I will make another PR on fixing this...
![image](https://user-images.githubusercontent.com/17893605/143910920-73fe8acf-9fcd-4a97-83b7-a568dfc07faa.png)

**Comment by ChiaChing-Yen** [comment]
https://compas.dev/compas/latest/ is now giving a HTTP 404 error

**Comment by tomvanmele** [comment]
yes we overlooked this :)

@licini

* `latest` is the latest released version. in this case `1.12.1`
* `dev` is the unreleased repo
* we only keep the latest patch of every released minor

last "rule" is not as important for now

**Comment by tomvanmele** [comment]
we cannot solve this with a simple redirect to the latest version number because there are page links like https://compas.dev/compas/.../installation.index.html where this will not work

**Comment by gonzalocasas** [comment]
this issue is solved afaics
