### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [compas-dev/compas#935]
# Feature Request
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

## Details
Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/COMPAS/lokal -name '*.py')
```

:crystal_ball: How will the development interests evolve further also according to update candidates in 40 lines of this software?

**Comment by jf---** [comment]
@tomvanmele || @gonzalocasas -1

**Comment by elfring** [comment]
:thinking: I find that [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13) can indicate also motivation for another bit of collateral evolution.

**Comment by tomvanmele** [comment]
hi @elfring 

i am not against implementing more of the magic dunder methods for some of the objects, but just so we are talking about the same thing, could you give a few examples of implementations you would like to see included?

**Comment by elfring** [comment]
:crystal_ball: Would you dare to apply a variant of the shown Perl command example on another development repository?

**Comment by gonzalocasas** [comment]
@elfring a PR with these changes would be welcome, but otherwise, this is a very low prio change, so I'll proceed to close. Feel free to keep commenting here if you feel you need additional clarifications.
