### ISSUE TITLE
RhinoMesh.from_geometry(M).to_compas() throws Runtime error (TypeErrorException)

### ISSUE THREAD

**Issue by ChiaChing-Yen** [compas-dev/compas#936]
**Describe the bug**
Collision Mesh Grasshopper component form COMPAS FAB doesn't work after recent updates. I tried isolating the issue and it turns out that `RhinoMesh.from_geometry(M).to_compas()` is throwing error. Same happens to `RhinoPoint.from_grometry(P).to_compas()`. Yet `RhinoMesh.from_guid(M).to_compas()` is working normally with the correct type hint.

**To Reproduce**
1. open Grasshopper Python script editor, set input name as 'M' and type hint as 'no type hint' or 'Mesh'
2. 
```python
from compas_rhino.geometry import RhinoMesh

a = RhinoMesh.from_geometry(M).to_compas()
```
3. input any Rhino mesh to the input 'M', I use a default mesh box from GH components.
4. 
```
  Error: Runtime error (TypeErrorException): unbound method to_compas() must be called with RhinoMesh instance as first argument (got nothing instead)

Traceback:
  line 3, in script
```

**Expected behavior**
It is supposed to return a compas mesh.

**Screenshots**
<img width="648" alt="Screenshot 2021-11-29 at 09 34 55" src="https://user-images.githubusercontent.com/60199319/143797259-ea2c4e74-de4e-4776-82fa-7aa1a02c207d.png">

**Desktop:**
 - OS: macOS 12.0.1 and Win11 Enterprise
 - Python version: 3.7.12
 - Python package manager : conda 4.11

**Additional context**
 - Rhino 7.12.21313.06342
 - compas 1.12.0
 - compas_fab 0.20.1

**Comment by tomvanmele** [comment]
this is indeed a bug and is fixed in the dev version on github since [6e5a48](https://github.com/compas-dev/compas/commit/6e5a4806977fd305f58c4d12debf5dfeb8be3e42) but it is not released yet...

**Comment by ChiaChing-Yen** [comment]
Good to know! Thank you COMPAS dev team for addressing this issue!

**Comment by tomvanmele** [comment]
could you test version `1.12.1` and confirm that the problem is indeed resolved?
thanks

**Comment by ChiaChing-Yen** [comment]
I updated to `1.12.1` and test the following methods with the steps I mentioned in the first comment:

* `RhinoPoint.from_geometry(M).to_compas()`
* `RhinoVector.from_geometry(M).to_compas()`
* `RhinoLine.from_geometry(M).to_compas()`
* `RhinoPlane.from_geometry(M).to_compas()`
* `RhinoMesh.from_geometry(M).to_compas()`

They all works as I expected, and the COMPAS FAB's components are working well, too.
I didn't test them with sophisticated test tools, yet from my point of view the problem are resolved.

**Comment by tomvanmele** [comment]
cool thanks
