### ISSUE TITLE
Feature Request: Proxy communication time

### ISSUE THREAD

**Issue by trtku** [compas-dev/compas#948]
# Feature Request

As a user, I want a built-in method of Proxy so that we can measure communication time of Proxy.

## Details

**Is your feature request related to a problem? Please describe.**
No, it's an improvement than a problem.

**Describe the solution you'd like**
A built-in method to calculate the communication time of Proxy. This can be a part of its profile attribute.

**Describe alternatives you've considered**
a tictac method with time module, though this might contain the calculation time; which might be a helpful built-in method as well.

**Additional context**
As a fan of COMPAS, I'm curious how fast the pure proxy is.
Again, this is for improvement, not urgent at all : )
This is my first feature request, so please let me know if there's something wrong.

**Comment by jf---** [comment]
@tomvanmele stale pls close
