### ISSUE TITLE
Blender installation does not work on Windows dus to inability to locate DLLs

### ISSUE THREAD

**Issue by tomvanmele** [compas-dev/compas#995]
**Describe the bug**

**To Reproduce**
1. Context [e.g. ST3, Rhino, Blender, ...]
2. Sample script
3. Sample data

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python version [e.g. 2.7]
 - Python package manager [e.g. macports, pip, conda]

**Additional context**

**Comment by tomvanmele** [comment]
the following worked on my windows laptop...
using the normal command line (not anaconda prompt)
with admin privileges

1. (this is just for convenience) add Blender `python\bin` to the `PATH`
2. make sure there are no other Pythons on the `PATH` (`where python`)
3. `python -m ensurepip`
4. `python -m pip install --upgrade pip`
5. `python -m pip install compas`

**Comment by tomvanmele** [comment]
@Licini could you try this on your machine?

**Comment by tomvanmele** [comment]
this might also be related
https://github.com/ContinuumIO/anaconda-issues/issues/11994

**Comment by gonzalocasas** [comment]
Is it really needed to include `ensurepip` and `--upgrade pip`? Since Blender ships with a decently updated python, isn't it irrelevant and perhaps even negative to force an update?

**Comment by tomvanmele** [comment]
no, but running this now again on a fresh windows installation, i had to even modify the prefix to make sure windows doesn't keep adding stuff to the roaming profile.

```bash
cd "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python"
.\bin\python.exe -m pip install compas --prefix="." --force-reinstall
```

**Comment by jf---** [comment]
> Since Blender ships with a decently updated python, isn't it irrelevant and perhaps even negative to force an update?

+1

@gonzalocasas lets keep weeding the tracker ;)

**Comment by tomvanmele** [comment]
see https://compas.dev/compas/latest/userguide/cad.blender.html
